// Real production server for the built frontend -- required now that routing is path-based
// (/shop/geisha-panama) rather than hash-based (#/shop/geisha-panama). A browser never sends the
// part of a URL after '#' in an HTTP request at all, so hash routing never needed any server-side
// awareness of which "page" was being requested -- every request was simply for '/'. Real paths
// change that: without this server explicitly falling back to index.html for any path Vite didn't
// build a real file for, a direct link or a page refresh on any non-home route would 404, since
// there's no actual file on disk at e.g. /shop/geisha-panama -- that route only exists client-side,
// resolved by React after index.html has already loaded and run.
//
// Also does real per-page meta tag injection for crawlers that don't execute JS (social link
// previews -- Facebook, Twitter/X, LinkedIn -- and some SEO crawlers), which is the actual reason
// this migration from hash routing happened. This is deliberately NOT full server-side rendering
// of the React app itself (a much larger undertaking) -- just the meta tags a crawler actually
// reads, mirroring the same PAGE_META table and per-item logic App.jsx already uses client-side
// (see getPageMeta in App.jsx and PAGE_META in src/data/index.js) so the two can't drift apart
// without both being touched.

const express = require("express");
const helmet = require("helmet");
const fs = require("fs");
const path = require("path");
const { PAGE_META, SLUG_TO_PAGE, KNOWN_ROUTES, PRODUCTS, MOMENTS, BREW_GUIDES, COUNTRIES, GROWING_FACTORS } = require("./dist-data/routeMeta.cjs");

const app = express();
const DIST_DIR = path.join(__dirname, "dist");
const PRERENDER_DIR = path.join(__dirname, "dist-prerendered");
const INDEX_HTML = fs.readFileSync(path.join(DIST_DIR, "index.html"), "utf8");

// Real static HTML snapshots of the actual rendered app, generated by scripts/prerender.mjs
// (see that file for why -- short version: this is a pure client-side SPA, so without this a
// crawler that doesn't run JS only ever sees the generic #ma-preload loading shell for every
// page, which is the direct cause of Search Console showing most known pages as not indexed).
// dist-prerendered/ is optional and gitignored -- it's produced by a build step that needs real
// network access this deploy environment may or may not have at build time, so its absence must
// never break serving: every route below falls straight back to the plain shell it already used,
// exactly as before this change, whenever no snapshot exists for that path.
function loadPrerenderedSnapshot(urlPath) {
  const clean = urlPath.split("?")[0].replace(/^\/+/, "").replace(/\/+$/, "");
  const relFile = clean === "" ? "index.html" : `${clean}.html`;
  const filePath = path.join(PRERENDER_DIR, relFile);
  // Guard against path traversal from a crafted request path before ever touching the
  // filesystem -- resolved path must stay inside PRERENDER_DIR.
  if (!filePath.startsWith(PRERENDER_DIR + path.sep) && filePath !== PRERENDER_DIR) return null;
  try {
    return fs.readFileSync(filePath, "utf8");
  } catch {
    return null;
  }
}

function escapeHtml(s) {
  return String(s).replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
}

// Same simple slugify as src/utils/helpers.js -- inlined rather than required directly, since
// that file is an ES module bundled by Vite for the browser, the same reason routeMeta.cjs itself
// exists rather than this script requiring src/data/index.js directly.
function slugify(s) {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}

const suffix = " | Morning Aroma";

// Real backend base URL -- same VITE_API_URL Railway env var the frontend itself uses to reach
// this exact backend (see src/utils/api.js). This process is a plain Node server, not a Vite
// build, so it can't read import.meta.env, but Railway exposes every service's env vars to every
// other service in the same environment, so the same variable name is readable here via
// process.env just as plainly. Used below to fetch real, live course/blog-post data for meta tags
// -- something this file could never do for course data before, and the reason course pages fell
// all the way back to the generic Academy hub meta (see the old comment on resolveMeta's "course"
// branch, still true for the case this fetch itself fails).
const API_URL = process.env.VITE_API_URL || process.env.BACKEND_URL || "";

// Tiny in-memory cache -- real course/blog-post content changes rarely (an admin edit, at most a
// few times a day), so refetching the full list on every single request would be real, wasted
// load against the live database for content that's virtually always identical to the last
// request's. 5 minutes balances "an admin's edit shows up in meta tags reasonably soon" against
// "don't hammer the backend on every crawler hit." Keyed by kind ("courses"/"blogposts") since
// they're two independent lists with two independent fetches and cache lifetimes.
const META_CACHE_TTL_MS = 5 * 60 * 1000;
const metaCache = new Map();

async function fetchJsonCached(cacheKey, url) {
  const cached = metaCache.get(cacheKey);
  if (cached && Date.now() - cached.fetchedAt < META_CACHE_TTL_MS) return cached.data;
  try {
    const res = await fetch(url, { signal: AbortSignal.timeout(5000) });
    if (!res.ok) throw new Error(`${res.status}`);
    const data = await res.json();
    metaCache.set(cacheKey, { data, fetchedAt: Date.now() });
    return data;
  } catch (err) {
    // A failed fetch (backend momentarily down, no API_URL configured, network hiccup) falls back
    // to whatever's cached, however stale, rather than nothing -- stale-but-real meta still beats
    // the generic hub fallback most of the time. Only truly returns null if nothing has ever been
    // fetched successfully yet (e.g. right after a fresh deploy's first request).
    console.error(`server.cjs: failed to fetch ${cacheKey} for meta tags:`, err.message || err);
    return cached ? cached.data : null;
  }
}

// Mirrors App.jsx's getPageMeta, for every route type that data is actually available for at
// build time -- product, moment, brewguide, country, growingfactor, and growingprofile (which
// shares product's own data) -- plus, now, "course" and "blogpost", fetched live from the real
// backend (see fetchJsonCached above) rather than from build-time static data, since both are
// genuinely database-driven content this script has no other way to read. Async because of that
// real network fetch; every call site below already awaits it.
async function resolveMeta(pageRoute) {
  const { page, id } = pageRoute;
  if ((page === "product" || page === "growingprofile") && id) {
    const p = PRODUCTS.find((p) => p.id === id);
    if (p) return { title: `${p.name} — ${p.country}${suffix}`, description: p.note };
    return PAGE_META[page === "product" ? "shop" : "growing"];
  }
  if (page === "moment" && id) {
    const m = MOMENTS.find((m) => m.id === id);
    return m ? { title: `${m.name}${suffix}`, description: m.benefit } : PAGE_META.moments;
  }
  if (page === "brewguide" && id) {
    const b = BREW_GUIDES.find((b) => slugify(b.name) === id);
    return b ? { title: `${b.name} Brew Guide${suffix}`, description: b.flavor } : PAGE_META.brewguides;
  }
  if (page === "country" && id) {
    const c = COUNTRIES.find((c) => slugify(c.name) === id);
    return c ? { title: `${c.name}${suffix}`, description: c.climate } : PAGE_META.growing;
  }
  if (page === "growingfactor" && id) {
    const f = GROWING_FACTORS.find((f) => slugify(f.name) === id);
    return f ? { title: `${f.name}${suffix}`, description: f.explain } : PAGE_META.growing;
  }
  // Real course data lives in the database -- only a list endpoint exists (no GET /courses/:id),
  // so this fetches the whole catalog (cached, see fetchJsonCached) and finds the matching one.
  // Courses are few enough that fetching the full list is cheap and the cache keeps it from being
  // refetched on every request anyway.
  if (page === "course" && id && API_URL) {
    const data = await fetchJsonCached("courses", `${API_URL}/courses`);
    const c = data && Array.isArray(data.courses) ? data.courses.find((c) => c.id === id) : null;
    if (c) return { title: `${c.name}${suffix}`, description: c.blurb };
    return PAGE_META.academy;
  }
  if (page === "course") return PAGE_META.academy;
  // Real blog posts, fetched by their own real slug via the public GET /blog/:slug endpoint --
  // unlike courses, this genuinely returns exactly the one post needed, no full-list fetch or
  // client-side find() required. Not run through fetchJsonCached (that cache is keyed for a
  // *list* shared across every request; a per-slug cache would need its own map keyed by slug --
  // not worth the complexity for a page type crawled far less often than the product catalog).
  // A missing/unpublished slug (404) or a fetch failure both fall back to the blog index's own
  // meta -- genuinely about the blog, unlike the pre-fix fallback which was silently the homepage's.
  if (page === "blogpost" && id && API_URL) {
    try {
      const res = await fetch(`${API_URL}/blog/${encodeURIComponent(id)}`, { signal: AbortSignal.timeout(5000) });
      if (res.ok) {
        const { post } = await res.json();
        if (post) return { title: `${post.title}${suffix}`, description: post.excerpt || post.title };
      }
    } catch (err) {
      console.error(`server.cjs: failed to fetch blog post "${id}" for meta tags:`, err.message || err);
    }
    return PAGE_META.blog || PAGE_META.home;
  }
  if (page === "blogpost") return PAGE_META.blog || PAGE_META.home;
  return PAGE_META[page] || PAGE_META.home;
}

function parseRoutePath(urlPath) {
  const raw = urlPath.replace(/^\/+/, "").split("?")[0];
  if (!raw) return { page: "home" };
  const [slug, rawId] = raw.split("/");
  const page = SLUG_TO_PAGE[slug];
  if (!page || !KNOWN_ROUTES.has(page)) return { page: "home" };
  return rawId ? { page, id: decodeURIComponent(rawId) } : { page };
}

// Real, live production domain by default -- matches the same SITE_ORIGIN pattern and fallback
// already established in scripts/generate-sitemap.mjs, not a placeholder or a wrong domain.
const SITE_ORIGIN = process.env.SITE_ORIGIN || "https://morning-aroma.com";

// Mirrors the real content of src/pages/Misc.jsx's PrivacyPolicyPage -- kept here as plain HTML
// specifically so it can be injected server-side for /privacy (see renderIndexWithMeta below).
// /privacy is otherwise a client-side-only React route, meaning any crawler that doesn't execute
// JavaScript -- including, per Google's own documented verification requirements, their OAuth
// consent screen homepage/privacy-policy checker -- would see the exact same empty loading shell
// for /privacy as for every other route, and never see the Google user data disclosure Google
// specifically scans for. If the policy text in Misc.jsx changes, update this to match.
const PRIVACY_POLICY_STATIC_HTML = `
  <div style="text-align:left; max-width: 640px; font-size: 0.85rem; line-height: 1.6; margin-top: 12px;">
    <h2>Privacy Policy</h2>
    <h3>What we collect</h3>
    <p>When you use Morning Aroma, we collect information you give us directly: your name and
    email when you create an account or sign in (including, if you choose, via "Sign in with
    Google" -- see below); shipping details at checkout; the notes, ratings, and varieties you log
    in My Aroma Journey; messages you send through our contact and inquiry forms or live chat; and
    reviews submitted through "Leave Your Aroma," which are anonymous and not linked to your
    account. We do not collect or store your full payment card details ourselves -- payment is
    processed directly by Paystack, and we only receive confirmation of whether a payment
    succeeded.</p>
    <h3>How we use it</h3>
    <p>We use this information to fulfil orders, respond to inquiries, personalize recommendations
    based on your tasting history, and improve the site. We do not sell your personal information
    to third parties.</p>
    <h3>Third-party services we use</h3>
    <p>Paystack processes all real payments and subscriptions. Resend sends our transactional
    emails. Cloudinary hosts product and content photos. Sentry receives error reports, only after
    explicit consent, and never receives your IP address.</p>
    <p><strong>Google</strong> provides the optional "Sign in with Google" button. If you use it,
    our application accesses your name, email address, and profile photo from your Google account,
    so we can create or sign you into your Morning Aroma account. We do not access your contacts,
    files, or any other Google data, and we never post to your Google account on your behalf. Our
    use of information received from Google APIs adheres to the Google API Services User Data
    Policy, including the Limited Use requirements.</p>
    <h3>Data retention and your rights</h3>
    <p>You can request a copy of the data we hold about you, ask us to correct it, or ask us to
    delete your account and associated data, by contacting hello@morning-aroma.com. We retain order
    records as required for accounting and legal purposes; other data is kept only as long as your
    account is active or as needed to provide the service.</p>
    <h3>Children's privacy</h3>
    <p>Morning Aroma is not directed at children under 16, and we do not knowingly collect
    information from them.</p>
    <h3>Contact</h3>
    <p>Questions about this policy: hello@morning-aroma.com.</p>
  </div>
`;

async function renderIndexWithMeta(urlPath) {
  const meta = await resolveMeta(parseRoutePath(urlPath));
  const title = escapeHtml(meta.title);
  const description = escapeHtml(meta.description || "");
  // The real, current page's own URL -- was missing from this replacement list entirely before
  // this, meaning any crawler that doesn't execute JS (many social media link-preview bots: a
  // real, separate audience from Googlebot, which does run JS and would see the client-side fix
  // in useDocumentMeta) always saw the homepage's URL here, regardless of which page was actually
  // being shared. urlPath already excludes any query string (see parseRoutePath above).
  const realUrl = `${SITE_ORIGIN}${urlPath.split("?")[0]}`;
  // Prefer a real prerendered snapshot of this exact page's rendered content over the bare
  // index.html shell -- see loadPrerenderedSnapshot above and scripts/prerender.mjs for why.
  // Meta tags are still rewritten below exactly as for the plain shell, so the two mechanisms
  // (per-page meta injection, per-page content snapshot) stay independent and either can exist
  // without the other.
  const snapshot = loadPrerenderedSnapshot(urlPath);
  // A prerendered snapshot is a full static HTML capture from whenever `npm run prerender` last
  // ran, including its own <script src="/assets/index-HASH.js"> tag baked in at that moment.
  // dist-prerendered/ is gitignored and produced by a separate, manual build step (see the
  // comment above loadPrerenderedSnapshot) -- it is NOT regenerated by the normal build/deploy
  // pipeline (`npm run build` only runs generate-sitemap + vite build + generate-route-meta), so
  // on Railway it can persist across deploys on disk while dist/ itself gets rebuilt with a new
  // hashed bundle. Real, live bug this caused: a request for "/" or "/shop" would get this old
  // snapshot's stale script tag pointing at a JS file that no longer exists on disk (the new
  // build deleted it), so the browser's script load 404s, React never mounts, and the whole page
  // -- including the cookie-consent banner -- looks "frozen": everything is really just static
  // HTML with zero JS attached. Every other route (no snapshot on disk) instead fell through to
  // the in-memory INDEX_HTML below, which is always current, which is exactly why only the pages
  // WITH a snapshot broke while everything else kept working. Fix: always repoint the snapshot's
  // script tag(s) at whatever INDEX_HTML (the just-built, definitely-current dist/index.html)
  // is actually using right now, the same way title/meta tags are already rewritten below --
  // so a stale snapshot can never again ship a reference to a deleted JS bundle.
  // Only the real Vite entry bundle -- type="module", the tag Vite itself writes into
  // dist/index.html -- is rewritten. A prerendered snapshot's HTML can also contain unrelated
  // <script src> tags belonging to third-party widgets that were loaded into the page at
  // prerender time (e.g. a Google Translate widget script), which must be left completely alone.
  let html = snapshot;
  if (snapshot) {
    const freshModuleTag = INDEX_HTML.match(/<script\s+type="module"[^>]*\ssrc="([^"]*)"[^>]*>/);
    const freshSrc = freshModuleTag ? freshModuleTag[1] : null;
    if (freshSrc) {
      html = snapshot.replace(
        /(<script\s+type="module"[^>]*\ssrc=")[^"]*(")/,
        `$1${freshSrc}$2`
      );
    }
  } else {
    html = INDEX_HTML;
  }
  html = html
    .replace(/<title>.*?<\/title>/, `<title>${title}</title>`)
    .replace(/<meta name="description" content=".*?"\s*\/?>/, `<meta name="description" content="${description}" />`)
    .replace(/<meta property="og:title" content=".*?"\s*\/?>/, `<meta property="og:title" content="${title}" />`)
    .replace(/<meta property="og:description" content=".*?"\s*\/?>/, `<meta property="og:description" content="${description}" />`)
    .replace(/<meta property="og:url" content=".*?"\s*\/?>/, `<meta property="og:url" content="${realUrl}" />`)
    .replace(/<link rel="canonical" href=".*?"\s*\/?>/, `<link rel="canonical" href="${realUrl}" />`)
    .replace(/<meta name="twitter:title" content=".*?"\s*\/?>/, `<meta name="twitter:title" content="${title}" />`)
    .replace(/<meta name="twitter:description" content=".*?"\s*\/?>/, `<meta name="twitter:description" content="${description}" />`);
  if (urlPath.split("?")[0] === "/privacy") {
    html = html.replace(
      /(Privacy Policy<\/a>\s*<\/p>)/,
      `$1${PRIVACY_POLICY_STATIC_HTML}`
    );
  }
  return html;
}

// Same reasoning and same deliberate CSP omission as the backend API's own helmet setup
// (server/src/app.js) -- real, low-risk headers on every response this server sends (every real
// page a visitor loads goes through this server, not just the API), CSP left for a dedicated
// follow-up since getting it wrong here specifically risks breaking Google Fonts, Cloudinary/
// Unsplash images, or Paystack's checkout script loading on the actual pages people see.
//
// crossOriginOpenerPolicy is overridden from helmet's own default ("same-origin") to
// "same-origin-allow-popups" -- a real, live bug, not a hypothetical: helmet's default value
// process-isolates this page from anything it opens via window.open(), which severs
// window.opener on the popup's side. Google's own Sign In With Google button opens exactly such
// a popup (accounts.google.com, a different origin) and its own script tries to postMessage back
// through that now-severed opener reference -- confirmed directly as the actual cause of a
// completely blank popup with "Cannot read properties of null (reading 'postMessage')" in its
// console, reproduced consistently on the real production site. same-origin-allow-popups keeps
// the same process-isolation benefit for ordinary cross-origin navigations while specifically
// preserving the opener relationship for popups this page itself opens, which is exactly the
// carve-out documented for this exact scenario.
app.use(helmet({ contentSecurityPolicy: false, crossOriginOpenerPolicy: { policy: "same-origin-allow-popups" } }));

// Railway's own health check -- kept ahead of the SPA fallback so it always gets a real response
// regardless of what routes exist client-side, the same reasoning Railway's own SPA guide gives.
app.get("/health", (req, res) => res.json({ ok: true }));

// TEMPORARY diagnostic route -- lists what's actually on disk in dist/ and dist/assets/ in the
// running container right now, to debug a live mismatch between the JS filename index.html
// references and what express.static actually finds. Safe to remove once resolved: read-only,
// lists filenames only (no file contents), and reveals nothing not already visible by requesting
// the files directly.
app.get("/__debug-dist", (req, res) => {
  let distFiles = [];
  let assetsFiles = [];
  let indexHtmlScriptTag = null;
  try { distFiles = fs.readdirSync(DIST_DIR); } catch (e) { distFiles = [String(e)]; }
  try { assetsFiles = fs.readdirSync(path.join(DIST_DIR, "assets")); } catch (e) { assetsFiles = [String(e)]; }
  try {
    const liveIndexHtml = fs.readFileSync(path.join(DIST_DIR, "index.html"), "utf8");
    indexHtmlScriptTag = liveIndexHtml.match(/<script[^>]*src="[^"]+"[^>]*>/g);
  } catch (e) { indexHtmlScriptTag = String(e); }
  res.json({
    DIST_DIR,
    distFiles,
    assetsFilesCount: assetsFiles.length,
    assetsFiles,
    inMemoryIndexHtmlScriptTag: INDEX_HTML.match(/<script[^>]*src="[^"]+"[^>]*>/g),
    liveIndexHtmlScriptTag: indexHtmlScriptTag,
  });
});

// Fingerprinted build assets (Vite hashes filenames under /assets) are safe to cache forever --
// a new deploy produces new filenames, it never reuses one with different content.
app.use("/assets", express.static(path.join(DIST_DIR, "assets"), { immutable: true, maxAge: "1y" }));
app.use(express.static(DIST_DIR, { index: false }));

// Catch-all fallback: any path Vite didn't build a real file for (i.e. every client-side route)
// gets index.html, with real per-page meta tags injected based on the actual requested path.
// No path pattern here (not app.get("*", ...)) -- Express 5's underlying path-to-regexp no longer
// accepts a bare "*" wildcard at all (a real breaking change from Express 4), and path parameter
// extraction was never actually needed anyway, since req.path is read directly in the handler.
// A path-less app.use() runs for anything the two static-file middlewares above didn't already
// handle, which is exactly the fallback behavior this needs.
app.use(async (req, res) => {
  res.set("Content-Type", "text/html");
  // Must never be cached, by the browser or by Cloudflare (this domain is proxied through it) --
  // it references hashed JS filenames that change on every deploy, and those old files are gone
  // from the server the moment a new build replaces dist/. A stale cached copy of this exact page
  // pointing at now-deleted assets is what leaves a visitor stuck on the static loading screen
  // forever after a deploy, since the failed script load happens before any of the app's own code
  // -- including its own error handling -- ever gets a chance to run.
  res.set("Cache-Control", "no-store, must-revalidate");
  res.send(await renderIndexWithMeta(req.path));
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log(`Serving on port ${PORT}`));
