const express = require("express");
const crypto = require("crypto");
const { query } = require("../db");
const { verifyAndMarkOrderPaid } = require("../utils/paymentVerification");

const router = express.Router();

function requireSecretKey() {
  const key = process.env.PAYSTACK_SECRET_KEY;
  if (!key) throw new Error("PAYSTACK_SECRET_KEY is not set.");
  return key;
}

// Paystack signs the RAW request body with HMAC SHA512, keyed with the account's secret key --
// the same key already used for verifying transactions server-side, not a separate "webhook
// secret". Compares in constant time (crypto.timingSafeEqual) rather than a plain string/===
// compare, so an attacker probing this endpoint can't use response-time differences to guess a
// valid signature byte-by-byte. Requires the genuinely raw, unparsed body -- re-serializing an
// already-JSON-parsed object wouldn't byte-for-byte match what Paystack actually signed (key
// ordering, whitespace can differ), which would incorrectly reject real webhooks. That's the
// entire reason this route is mounted with express.raw() ahead of the global express.json() in
// app.js, rather than after it.
function isValidSignature(rawBody, signatureHeader) {
  if (!signatureHeader || typeof signatureHeader !== "string") return false;
  const expected = crypto.createHmac("sha512", requireSecretKey()).update(rawBody).digest("hex");
  const expectedBuffer = Buffer.from(expected, "utf8");
  const providedBuffer = Buffer.from(signatureHeader, "utf8");
  // timingSafeEqual throws if the two buffers are different lengths rather than just returning
  // false -- checking length first, and failing closed if they differ, rather than letting that
  // throw become an unhandled 500 on a security check.
  if (expectedBuffer.length !== providedBuffer.length) return false;
  return crypto.timingSafeEqual(expectedBuffer, providedBuffer);
}

router.post("/paystack", async (req, res) => {
  const rawBody = req.body; // a Buffer -- this route is mounted with express.raw(), not express.json()
  const signature = req.headers["x-paystack-signature"];

  if (!isValidSignature(rawBody, signature)) {
    // Deliberately vague, same principle as every other auth check in this app -- don't hand
    // whoever's probing this endpoint any detail that helps them iterate toward a forged one.
    return res.status(401).json({ error: "Invalid signature." });
  }

  let event;
  try {
    event = JSON.parse(rawBody.toString("utf8"));
  } catch {
    return res.status(400).json({ error: "Malformed payload." });
  }

  // Acknowledge quickly with 200 once the signature is confirmed genuine, even for event types
  // this app doesn't act on -- Paystack retries on anything other than 200, and retrying an event
  // type we're deliberately ignoring would just repeat forever for no reason.
  if (event.event !== "charge.success") {
    return res.status(200).json({ received: true });
  }

  const reference = event.data && event.data.reference;
  // This app generates references as `${orderNumber}-${timestamp}`, e.g. "MA-1000-173500..." (see
  // the frontend's Checkout.jsx). Extracting the order number back out to find the right order,
  // since unlike the frontend-triggered verify endpoint, a webhook has no user session to look one
  // up by -- Paystack is calling this directly, not a signed-in customer's browser.
  const match = typeof reference === "string" && reference.match(/^MA-(\d+)-/);
  if (!match) {
    // A reference that doesn't match this app's own format wasn't generated by this checkout --
    // nothing to do, but still acknowledge so Paystack doesn't keep retrying an event we can never
    // act on regardless of how many times it's redelivered.
    return res.status(200).json({ received: true });
  }

  const orderResult = await query("SELECT * FROM orders WHERE order_number = $1", [match[1]]);
  const order = orderResult.rows[0];
  if (!order) return res.status(200).json({ received: true }); // same reasoning as above

  const result = await verifyAndMarkOrderPaid(order, reference);
  // Always 200 once the event has genuinely been processed, whether or not it resulted in marking
  // the order paid -- "already paid" (the normal case: the frontend's own verify call beat this
  // webhook to it) and "genuinely couldn't verify" are both handled outcomes, not delivery
  // failures. A non-200 response here should mean "something on this server actually broke," not
  // "this particular event didn't lead to a state change" -- returning an error status for the
  // latter would make Paystack retry indefinitely for no reason.
  res.status(200).json({ received: true, verified: result.ok });
});

module.exports = router;
