-- Real per-lesson content for the 15 Academy courses seeded in 012_academy.sql -- previously
-- "lessons" on the courses table was only ever a bare count; there was no actual title or
-- description stored anywhere for any lesson, of any course. This adds that real content.

CREATE TABLE IF NOT EXISTS chapters (
  id            TEXT PRIMARY KEY,
  course_id     TEXT NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  number        INTEGER NOT NULL,
  title         TEXT NOT NULL,
  description   TEXT NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (course_id, number)
);

CREATE INDEX IF NOT EXISTS idx_chapters_course_id ON chapters (course_id);

INSERT INTO chapters (id, course_id, number, title, description) VALUES
('espresso-ch1', 'espresso', 1, 'The shot as a recipe', 'What dose, yield, and time actually mean, and why espresso is the one brew method defined by a ratio and a stopwatch, not a scoop.'),
('espresso-ch2', 'espresso', 2, 'Grind size and extraction', 'Why grind is the first thing to adjust, not pressure or temperature, and how to read a sour or bitter shot back to a grinder setting.'),
('espresso-ch3', 'espresso', 3, 'Dialing in step by step', 'A repeatable process for tightening a new bean in: starting ratio, tasting, adjusting one variable at a time.'),
('espresso-ch4', 'espresso', 4, 'Tamping and distribution', 'Why an even puck matters more than tamp pressure, and the channeling problems an uneven one causes.'),
('espresso-ch5', 'espresso', 5, 'Reading the pour', 'What a healthy pour looks like from first drips to the final ounce, and what a too-fast or too-slow pour is telling you.'),
('espresso-ch6', 'espresso', 6, 'Troubleshooting common faults', 'Sour, bitter, weak, and harsh shots -- matching each symptom to its most likely cause and fix.'),
('cappuccino-ch1', 'cappuccino', 1, 'The 1:1:1 ratio', 'Espresso, steamed milk, and microfoam in equal thirds -- what makes a cappuccino a cappuccino, not just a small latte.'),
('cappuccino-ch2', 'cappuccino', 2, 'Steaming for microfoam', 'Getting a tight, glossy texture rather than large bubbles: purge, angle, and where to hold the wand.'),
('cappuccino-ch3', 'cappuccino', 3, 'Stretching vs. texturing phases', 'The two distinct stages of steaming milk, and why skipping or rushing either one ruins the foam.'),
('cappuccino-ch4', 'cappuccino', 4, 'Pouring into a small cup', 'Working with a smaller volume and less room for error than a latte -- pace and pour height.'),
('cappuccino-ch5', 'cappuccino', 5, 'Serving and holding', 'How long a cappuccino holds its texture, and why it''s built to be served immediately, not staged ahead.'),
('latte-ch1', 'latte', 1, 'A different ratio, a different canvas', 'More milk, less foam than a cappuccino -- what that changes about texture and pour technique.'),
('latte-ch2', 'latte', 2, 'Stretching milk longer', 'Extending the aeration phase for a latte''s silkier microfoam without overshooting into froth.'),
('latte-ch3', 'latte', 3, 'Your first heart', 'Free pouring a heart: pitcher height, wiggle-free base pour, then the finishing push through.'),
('latte-ch4', 'latte', 4, 'Rosetta fundamentals', 'Building the wag motion that creates a rosetta''s leaves, and the common ways it collapses.'),
('latte-ch5', 'latte', 5, 'Tulip and layering', 'Stacking pours to build a tulip, and why layering control is really about pour speed, not the pitcher.'),
('flat-white-ch1', 'flat-white', 1, 'What makes it a flat white', 'A tighter milk texture and a higher coffee-to-milk ratio than a latte -- the espresso-forward middle ground.'),
('flat-white-ch2', 'flat-white', 2, 'Micro-texturing', 'Getting velvety, near-imperceptible microfoam rather than a visible foam cap.'),
('flat-white-ch3', 'flat-white', 3, 'Ristretto vs. standard shots', 'Why many flat whites use a shorter, more concentrated shot, and how that changes the final balance.'),
('flat-white-ch4', 'flat-white', 4, 'Pouring for a thinner foam layer', 'Adjusting your usual latte pour technique for a drink with much less foam to work with.'),
('mocha-ch1', 'mocha', 1, 'Balancing three flavors', 'Chocolate, espresso, and steamed milk -- why most mochas either bury the coffee or taste like watered-down cocoa.'),
('mocha-ch2', 'mocha', 2, 'Choosing and building your chocolate base', 'Cocoa vs. chocolate syrup, sweetness levels, and how much to use relative to your shot.'),
('mocha-ch3', 'mocha', 3, 'Order of operations', 'Why what goes into the cup first changes how well the chocolate actually integrates with the espresso.'),
('mocha-ch4', 'mocha', 4, 'Finishing touches', 'Whipped cream, drizzle, and other mocha finishes -- and when to skip them.'),
('americano-ch1', 'americano', 1, 'Water ratio and body', 'How much water to add, and why an americano isn''t just ''diluted espresso'' when done right.'),
('americano-ch2', 'americano', 2, 'Pour order changes the cup', 'Espresso-into-water vs. water-into-espresso -- the crema and body differences between the two.'),
('americano-ch3', 'americano', 3, 'Hot vs. iced americanos', 'Adjusting ratio and ice for a version that doesn''t taste watered-down once it melts.'),
('cold-brew-ch1', 'cold-brew', 1, 'Steep ratio fundamentals', 'Coffee-to-water ratios for concentrate vs. ready-to-drink, and why cold brew needs a coarser grind than you''d expect.'),
('cold-brew-ch2', 'cold-brew', 2, 'Steep time and temperature', 'How long is long enough, and why steeping cold brew even longer isn''t the same lever as brewing hotter coffee stronger.'),
('cold-brew-ch3', 'cold-brew', 3, 'Filtration methods', 'Cloth, paper, and mesh filtration, and the tradeoffs each makes in clarity vs. speed vs. body.'),
('cold-brew-ch4', 'cold-brew', 4, 'Building a concentrate menu', 'Scaling a single batch into multiple drinks -- dilution ratios, milk versions, and shelf life.'),
('turkish-ch1', 'turkish', 1, 'The cezve and fine grind', 'Why Turkish coffee needs a grind finer than espresso, and what happens if it isn''t.'),
('turkish-ch2', 'turkish', 2, 'Building the foam cap (kaymak)', 'The slow-heat technique that raises foam to the surface before the coffee ever boils.'),
('turkish-ch3', 'turkish', 3, 'Brewing without a boil', 'Controlling heat to bring the coffee just to the point of foaming, not a rolling boil, across multiple pours.'),
('turkish-ch4', 'turkish', 4, 'Serving tradition and technique', 'Settling grounds, pouring foam first, and the etiquette that goes with a proper serve.'),
('vietnamese-ch1', 'vietnamese', 1, 'The phin filter, step by step', 'Bloom, fill, and slow drip -- the mechanics of brewing through a small metal filter.'),
('vietnamese-ch2', 'vietnamese', 2, 'Condensed milk ratios', 'Balancing sweetness against a strong, dark roast base -- hot vs. iced ratios differ.'),
('vietnamese-ch3', 'vietnamese', 3, 'Serving hot or over ice', 'Adjusting drip time and condensed milk for ca phe nong vs. ca phe da.'),
('moka-pot-ch1', 'moka-pot', 1, 'How a moka pot actually extracts', 'Steam pressure pushing water through grounds -- why it isn''t real espresso, and what it does well instead.'),
('moka-pot-ch2', 'moka-pot', 2, 'Grind size and fill level', 'The specific grind and basket-fill mistakes that cause the classic burnt, bitter moka pot cup.'),
('moka-pot-ch3', 'moka-pot', 3, 'Heat control on the stove', 'Managing flame or burner heat through the whole brew to avoid scorching the last of the extraction.'),
('affogato-ch1', 'affogato', 1, 'Timing the pour', 'Why the shot needs to hit the ice cream while it''s still hot, and how fast the whole drink comes together.'),
('affogato-ch2', 'affogato', 2, 'Glassware and scoop choice', 'Vessel size, ice cream density, and how they change how the drink melts and eats.'),
('home-brewing-ch1', 'home-brewing', 1, 'Choosing a method for your kitchen', 'Matching pour-over, French press, or Aeropress to your equipment, time, and taste preference.'),
('home-brewing-ch2', 'home-brewing', 2, 'Grind size across methods', 'Why the same bean needs a different grind for each brewer, and how to dial that in at home.'),
('home-brewing-ch3', 'home-brewing', 3, 'Pour-over fundamentals', 'Bloom, pour rate, and total brew time for a clean, balanced cup with a V60 or similar dripper.'),
('home-brewing-ch4', 'home-brewing', 4, 'French press technique', 'Steep time, plunge technique, and why French press body comes from what it doesn''t filter out.'),
('home-brewing-ch5', 'home-brewing', 5, 'Aeropress fundamentals', 'Standard vs. inverted method, and how pressure and steep time interact in a small brew.'),
('home-brewing-ch6', 'home-brewing', 6, 'Water quality and temperature', 'Why the water itself changes your cup as much as the beans do, and what temperature range to aim for.'),
('home-brewing-ch7', 'home-brewing', 7, 'Building a home routine', 'Putting it together: a repeatable weekday routine and how to adjust it bean to bean.'),
('sensory-cupping-ch1', 'sensory-cupping', 1, 'Why cupping exists', 'The standardized method that lets professionals compare coffees fairly, and what it''s actually measuring.'),
('sensory-cupping-ch2', 'sensory-cupping', 2, 'Setting up a cupping table', 'Grind, water ratio, and timing for a proper cupping session, whether for two coffees or ten.'),
('sensory-cupping-ch3', 'sensory-cupping', 3, 'Aroma: dry and wet', 'What to smell for at each stage, before and after breaking the crust, and why it comes first.'),
('sensory-cupping-ch4', 'sensory-cupping', 4, 'Tasting for acidity and body', 'Learning to distinguish brightness from sourness, and light body from thin, underextracted coffee.'),
('sensory-cupping-ch5', 'sensory-cupping', 5, 'Naming aftertaste and finish', 'What separates a clean finish from a lingering one, and vocabulary for describing what''s left in your mouth.'),
('sensory-cupping-ch6', 'sensory-cupping', 6, 'Scoring and comparing coffees', 'Using a simple scoresheet to compare coffees side by side, not just describe them individually.'),
('roasting-fundamentals-ch1', 'roasting-fundamentals', 1, 'From green to roasted', 'What actually happens to a coffee bean under heat, and the phases every roast passes through.'),
('roasting-fundamentals-ch2', 'roasting-fundamentals', 2, 'First crack and what it means', 'The audible, physical marker every roaster times against, and why it matters more than color alone.'),
('roasting-fundamentals-ch3', 'roasting-fundamentals', 3, 'Development time', 'The window after first crack that shapes flavor the most, and how it differs between light and dark roasts.'),
('roasting-fundamentals-ch4', 'roasting-fundamentals', 4, 'Roast curves', 'Reading a temperature curve over time, and what a flat spot or a stall actually tells you.'),
('roasting-fundamentals-ch5', 'roasting-fundamentals', 5, 'Light, medium, and dark roast profiles', 'How roast level trades off acidity, body, and origin character -- and why darker isn''t ''more roasted flavor,'' it''s different flavor.'),
('roasting-fundamentals-ch6', 'roasting-fundamentals', 6, 'Cooling and resting', 'Why cooling speed matters immediately after roasting, and why beans need days to rest before they taste their best.'),
('roasting-fundamentals-ch7', 'roasting-fundamentals', 7, 'Common roasting faults', 'Baking, scorching, and underdevelopment -- what causes each, and how to hear or taste it.'),
('roasting-fundamentals-ch8', 'roasting-fundamentals', 8, 'Building a roast log', 'Tracking your roasts so you can repeat a good one and diagnose a bad one.'),
('cafe-management-ch1', 'cafe-management', 1, 'Costing a menu item', 'Real ingredient, labor, and overhead costs behind a single drink, not just the price of the beans.'),
('cafe-management-ch2', 'cafe-management', 2, 'Pricing for margin', 'Setting menu prices that actually cover your costs and leave room for a real margin.'),
('cafe-management-ch3', 'cafe-management', 3, 'Staffing a shift', 'Matching staff levels to real demand patterns instead of guessing, and what overstaffing actually costs you.'),
('cafe-management-ch4', 'cafe-management', 4, 'Training baristas consistently', 'Building a training process so quality doesn''t depend on which barista is on shift.'),
('cafe-management-ch5', 'cafe-management', 5, 'Inventory and waste', 'Tracking stock and spoilage so ordering is based on real usage, not habit.'),
('cafe-management-ch6', 'cafe-management', 6, 'Designing a menu', 'Balancing variety against what your team can actually execute consistently during a rush.'),
('cafe-management-ch7', 'cafe-management', 7, 'Managing a rush', 'Workflow and station design for staying in control when a line forms, not just when it''s quiet.'),
('cafe-management-ch8', 'cafe-management', 8, 'Customer experience basics', 'The small, repeatable things that make people come back, beyond just the coffee itself.'),
('cafe-management-ch9', 'cafe-management', 9, 'Reading your own numbers', 'The handful of real numbers -- not vanity metrics -- worth checking every week to know how the business is actually doing.')
ON CONFLICT (id) DO NOTHING;

-- Total chapters seeded: 73, across 15 courses
