-- Real quiz questions for a complete vertical slice of 3 courses (Espresso, Home Brewing,
-- Roasting Fundamentals) -- one real multiple-choice question per chapter, with plausible
-- wrong answers and a real explanation, not filler. The remaining 12 courses have no
-- questions seeded yet; admins can add them through the new Manage Quiz UI (see
-- src/admin/index.jsx), the same pattern already established for chapters themselves.

CREATE TABLE IF NOT EXISTS quiz_questions (
  id            TEXT PRIMARY KEY,
  chapter_id    TEXT NOT NULL REFERENCES chapters(id) ON DELETE CASCADE,
  number        INTEGER NOT NULL DEFAULT 1,
  question      TEXT NOT NULL,
  options       TEXT[] NOT NULL,
  correct_index INTEGER NOT NULL,
  explanation   TEXT NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (chapter_id, number)
);

CREATE INDEX IF NOT EXISTS idx_quiz_questions_chapter_id ON quiz_questions (chapter_id);

-- One real attempt record per submission -- a user can retake a chapter's quiz any number
-- of times; the frontend/admin can decide whether to show best score or latest, but every
-- real attempt is kept, not overwritten, so that choice is never constrained by the schema.
CREATE TABLE IF NOT EXISTS quiz_attempts (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       UUID NOT NULL REFERENCES users(id),
  chapter_id    TEXT NOT NULL REFERENCES chapters(id) ON DELETE CASCADE,
  score         INTEGER NOT NULL, -- 0-100, percentage correct
  passed        BOOLEAN NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_quiz_attempts_user_chapter ON quiz_attempts (user_id, chapter_id);

INSERT INTO quiz_questions (id, chapter_id, number, question, options, correct_index, explanation) VALUES
('espresso-ch1-q1', 'espresso-ch1', 1, 'In espresso, what does the ''yield'' in a recipe refer to?', ARRAY['The weight of dry grounds used', 'The weight or volume of liquid espresso produced', 'The total brew time in seconds', 'The water temperature at the group head'], 1, 'Yield is the output -- how much liquid espresso comes out. Dose is the input (dry grounds), and ratio is yield divided by dose.'),
('espresso-ch2-q1', 'espresso-ch2', 1, 'A shot pulls too fast and tastes sour. What''s the most likely first fix?', ARRAY['Grind coarser', 'Grind finer', 'Use less coffee (lower the dose)', 'Use colder water'], 1, 'A fast, sour shot is usually underextracted. A finer grind slows the flow and increases extraction, which is the first thing to adjust.'),
('espresso-ch3-q1', 'espresso-ch3', 1, 'When dialing in a new bean, what''s the recommended approach?', ARRAY['Change grind, dose, and time all at once to save time', 'Adjust one variable at a time and taste between changes', 'Only ever adjust the tamp pressure', 'Match the settings that worked for the previous bean exactly'], 1, 'Changing multiple variables at once makes it impossible to know which change actually caused a difference in the cup.'),
('espresso-ch4-q1', 'espresso-ch4', 1, 'Why does an uneven puck (poor distribution) cause problems, even with a good tamp?', ARRAY['It makes the portafilter harder to lock in', 'It causes channeling, where water finds the path of least resistance through thinner areas', 'It always makes the shot too slow', 'It has no real effect on extraction'], 1, 'Water follows the easiest path. Uneven distribution creates thin spots that overextract while denser areas stay underextracted, both at once.'),
('espresso-ch5-q1', 'espresso-ch5', 1, 'What does a very pale, fast-thinning pour partway through a shot usually indicate?', ARRAY['A perfectly balanced extraction', 'Channeling or the shot running out of extractable flavor too early', 'The grind is too fine', 'The dose is too high'], 1, 'Pouring pale early on is a sign water is rushing through with little resistance -- classic channeling, or a shot pulled well past its useful yield.'),
('espresso-ch6-q1', 'espresso-ch6', 1, 'A shot tastes bitter and harsh. Besides grind, what''s a common cause worth checking?', ARRAY['Water that''s too cold', 'Overly stale, over-roasted, or over-extracted coffee', 'Too little coffee in the basket', 'A grind that''s too coarse'], 1, 'Bitterness often comes from overextraction (grind too fine, time too long) or from the roast itself being very dark or stale, not just one single variable.'),
('home-brewing-ch1-q1', 'home-brewing-ch1', 1, 'Which factor matters most when choosing between pour-over, French press, and Aeropress at home?', ARRAY['Only the price of the equipment', 'Your available time, desired body/clarity, and cleanup tolerance', 'Whichever method uses the least coffee', 'Only the color of the final cup'], 1, 'Each method trades off time, body, and clarity differently -- there''s no single ''best'' method, only the best fit for how you actually want to brew.'),
('home-brewing-ch2-q1', 'home-brewing-ch2', 1, 'Why does the same bean need a different grind size for a French press versus a pour-over?', ARRAY['It doesn''t -- grind size never needs to change', 'Immersion methods like French press need a coarser grind to avoid over-extraction and sediment', 'Pour-over always requires a coarser grind than French press', 'Grind size only affects color, not extraction'], 1, 'French press grounds sit in full contact with water for minutes with no paper filter, so a coarser grind avoids over-extraction and keeps sediment out of the cup.'),
('home-brewing-ch3-q1', 'home-brewing-ch3', 1, 'What is the ''bloom'' stage in pour-over brewing?', ARRAY['The final pour before serving', 'A short initial pour that lets trapped CO2 escape before the main extraction', 'Letting the coffee cool before drinking', 'Grinding the beans right before brewing'], 1, 'The bloom wets the grounds and releases CO2 that would otherwise interfere with even saturation during the rest of the pour.'),
('home-brewing-ch4-q1', 'home-brewing-ch4', 1, 'What does French press body come from, that a paper-filtered method doesn''t have?', ARRAY['Extra sugar dissolved during brewing', 'Fine sediment and oils that a metal mesh filter doesn''t remove', 'A longer roast time', 'Higher water temperature'], 1, 'Paper filters trap oils and fine particles; French press''s metal mesh lets them through, giving a fuller, heavier mouthfeel.'),
('home-brewing-ch5-q1', 'home-brewing-ch5', 1, 'What''s a key difference between standard and inverted Aeropress methods?', ARRAY['Inverted method uses no filter at all', 'Inverted method delays filtration until you flip it right before pressing, allowing a longer steep', 'Standard method always makes stronger coffee', 'There is no real difference between them'], 1, 'Inverting lets the coffee steep fully before any water can drip through, giving more control over contact time versus the standard method.'),
('home-brewing-ch6-q1', 'home-brewing-ch6', 1, 'Why can water quality noticeably change the taste of your coffee?', ARRAY['Water has no real effect on flavor', 'Minerals in water affect extraction and can add or mute flavors', 'Only the temperature of water matters, not its composition', 'Bottled water is always required for good coffee'], 1, 'Water chemistry (mineral content) affects how well flavors extract -- water that''s too soft or too hard both change the result, independent of temperature.'),
('home-brewing-ch7-q1', 'home-brewing-ch7', 1, 'What''s the main benefit of building a repeatable home brewing routine?', ARRAY['It guarantees every bean will taste identical', 'It gives you a consistent baseline to notice what changes when you adjust one variable', 'It removes the need to ever taste your coffee', 'It only matters for competition brewing'], 1, 'A consistent routine is what lets you actually tell whether a change (new bean, different grind) made a real difference, rather than guessing.'),
('roasting-fundamentals-ch1-q1', 'roasting-fundamentals-ch1', 1, 'What happens to a coffee bean''s structure during roasting?', ARRAY['Nothing changes except color', 'It undergoes chemical reactions and physical changes (moisture loss, expansion) that develop flavor', 'It only loses weight, with no chemical change', 'It becomes denser and smaller'], 1, 'Roasting drives off moisture, expands the bean, and triggers chemical reactions (like the Maillard reaction) that create the flavors and aromas we associate with coffee.'),
('roasting-fundamentals-ch2-q1', 'roasting-fundamentals-ch2', 1, 'What is ''first crack''?', ARRAY['The moment beans are loaded into the roaster', 'An audible, physical event caused by internal pressure and steam release as the bean structure changes', 'The final cooling stage after roasting', 'A defect that ruins the batch'], 1, 'First crack is a real, audible marker roasters listen for -- it signals a specific stage of internal pressure release, not a mistake.'),
('roasting-fundamentals-ch3-q1', 'roasting-fundamentals-ch3', 1, 'Why does ''development time'' (time after first crack) matter so much for flavor?', ARRAY['It has no effect on flavor at all', 'It''s the window where much of the roast''s final flavor character is shaped', 'It only affects the bean''s color, not taste', 'Longer development always means a lighter roast'], 1, 'The period after first crack is where a lot of flavor development happens -- too short can taste underdeveloped/grassy, too long pushes toward burnt/flat.'),
('roasting-fundamentals-ch4-q1', 'roasting-fundamentals-ch4', 1, 'What does a ''stall'' or flat spot on a roast curve usually indicate?', ARRAY['The roast is progressing perfectly on schedule', 'Heat applied isn''t keeping pace with the bean''s rate of temperature rise', 'The beans have finished roasting', 'The roaster needs more beans added'], 1, 'A flat or slowing curve means the applied heat isn''t keeping up with what the roast needs at that stage, which can lead to a baked, underdeveloped cup if not corrected.'),
('roasting-fundamentals-ch5-q1', 'roasting-fundamentals-ch5', 1, 'Why isn''t a dark roast simply ''more roasted flavor'' than a light roast?', ARRAY['Darker roasts are always more flavorful in every way', 'Roast level trades off different characteristics -- acidity and origin character for body and roast-driven flavors, not simply ''more'' of everything', 'Light roasts have no flavor at all', 'Roast level doesn''t actually change flavor'], 1, 'Darker roasts typically mute acidity and origin character in favor of roast-driven flavors and heavier body -- it''s a different flavor profile, not a stronger version of the same one.'),
('roasting-fundamentals-ch6-q1', 'roasting-fundamentals-ch6', 1, 'Why do beans need to rest for days after roasting, before tasting their best?', ARRAY['Resting has no real effect on taste', 'Beans continue releasing CO2 after roasting, and resting lets that settle before brewing', 'Resting only matters for very light roasts', 'Beans need to rest for months, not days'], 1, 'Freshly roasted beans are still off-gassing CO2, which can disrupt extraction (excessive bloom, uneven saturation) -- a short rest lets that settle.'),
('roasting-fundamentals-ch7-q1', 'roasting-fundamentals-ch7', 1, 'What commonly causes a ''baked'' tasting roast?', ARRAY['Roasting too hot and too fast', 'Too little heat over too long a time, often from an early stall in the roast', 'Cooling the beans too quickly', 'Using too much green coffee at once'], 1, 'Baking usually comes from insufficient heat stretched over too long a roast time, producing a flat, papery cup rather than a developed one.'),
('roasting-fundamentals-ch8-q1', 'roasting-fundamentals-ch8', 1, 'What''s the main reason to keep a roast log?', ARRAY['It''s required by law for commercial roasters', 'It lets you repeat a roast that worked and diagnose what went wrong in one that didn''t', 'It replaces the need to taste the coffee', 'It only matters if you roast the exact same bean forever'], 1, 'Without a record of what you actually did (times, temperatures, heat changes), you can''t reliably repeat a good roast or figure out what caused a bad one.')
ON CONFLICT (id) DO NOTHING;

-- Total questions seeded: 21, across 3 fully-covered courses
