-- Real content, learning objectives, and one real quiz question per lesson for all 52
-- remaining chapters (12 courses) -- completes real content across the entire Academy,
-- matching the same standard already established for the first 3 courses (Espresso, Home
-- Brewing, Roasting Fundamentals) in earlier migrations.

UPDATE chapters SET content = CASE id
  WHEN 'cappuccino-ch1' THEN 'The 1:1:1 ratio means equal parts espresso, steamed milk, and microfoam by volume -- roughly a third of your cup each. This is what separates a cappuccino from a latte, which uses far more steamed milk and only a thin foam cap.

Because each component is a genuine third of the drink, none of the three can be weak. A thin, watery shot shows through immediately with this little milk to hide behind. Flat, bubbly milk with no real microfoam leaves the drink feeling unfinished, since that foam layer is a full third of what you''re drinking.

Getting the ratio right starts with using a cup sized for it -- a true cappuccino is smaller than most people expect, usually 150-180ml, specifically so the thirds stay honest rather than getting diluted into something closer to a small latte.'
  WHEN 'cappuccino-ch2' THEN 'Microfoam is a tight, glossy texture with tiny, barely visible bubbles -- closer to wet paint than shaving cream. Large, visible bubbles mean the milk was aerated too aggressively or for too long, and they won''t integrate into a smooth pour.

Three things control this: purging the steam wand first (a quick blast to clear condensed water, which would otherwise spit and disrupt the surface), the angle you hold the pitcher at (typically creating a slight whirlpool rather than a still surface), and where in the milk you actually hold the wand tip.

The wand tip should sit just below the surface during the brief aeration phase, then move deeper for the rest of the steam. Held too shallow the whole time, you get coarse foam. Held too deep from the start, you get almost no aeration at all -- hot milk with barely any texture.'
  WHEN 'cappuccino-ch3' THEN 'Steaming milk actually happens in two distinct phases, and treating them as one is why a lot of home attempts turn out wrong. The first is stretching -- aerating the milk by holding the wand tip near the surface, which is where all your foam volume actually gets created.

The second is texturing: once you''ve stretched in enough air, the wand moves deeper to spin the milk into a whirlpool, breaking down any larger bubbles from the stretch phase into fine microfoam and warming the milk evenly.

Skip or rush the stretch, and you won''t have enough foam volume for a real cappuccino, no matter how well you texture afterward. Skip or rush the texturing, and you''re left with the coarse, uneven bubbles the stretch phase created, never refined into something smooth. Both phases need real, deliberate time -- typically stretching for just the first few seconds, then texturing for the remainder.'
  WHEN 'cappuccino-ch4' THEN 'Pouring into a cappuccino''s smaller cup leaves far less room for error than pouring a latte. There''s less total volume to work with, so a slightly off pour height or a wobble in your hand shows up immediately in the final look and layering.

Pour height matters more here than in almost any other milk drink: starting too high causes the milk to break through the crema rather than settling underneath it, muddying the surface before you''ve even begun. Starting close to the surface and gradually raising the pitcher as the cup fills gives you far more control over where the foam actually lands.

Because the volume is so small, the whole pour happens fast -- often under 10 seconds from start to finish. There''s little time to correct a mistake mid-pour, which is part of why cappuccino pouring is often considered harder to learn cleanly than a larger latte, despite looking simpler.'
  WHEN 'cappuccino-ch5' THEN 'A cappuccino''s texture doesn''t hold the way a coffee''s flavor does. Microfoam starts breaking down and separating from the liquid within a few minutes, which is why cappuccinos are built to order and served immediately, not staged ahead of a rush the way some other drinks might be.

This is a real, practical constraint: unlike a drip coffee or even an espresso shot, which can sit for a short while without much harm, a cappuccino that sits loses the exact quality that defines it. The foam layer visibly deflates, the milk and espresso start to separate, and what was a cohesive drink starts looking like three components that happened to end up in the same cup.

Serving immediately also means serving in the right vessel -- a cup that holds heat reasonably well, since the drink has no lid or extra volume of liquid to buffer against cooling the way a larger drink would.'
  WHEN 'latte-ch1' THEN 'A latte swaps the cappuccino''s equal thirds for a much higher proportion of steamed milk to a thin foam cap -- often just a few millimeters of foam on top of a large volume of silky milk. This isn''t simply "more milk," it changes the whole canvas you''re working with.

With so much more liquid volume relative to foam, a latte pour has real room to build shapes -- hearts, rosettas, tulips -- since there''s enough surface area and time during the pour to actually create them. A cappuccino''s small cup and thin margins don''t give you that same room.

The milk itself is also steamed differently as a result: since foam is a much smaller fraction of the final drink, less total aeration is needed during the stretch phase, with more of the steaming time spent on texturing a large volume of silky, well-integrated milk.'
  WHEN 'latte-ch2' THEN 'Because a latte''s foam layer is thin compared to its total milk volume, the stretching (aeration) phase runs longer than it would for a cappuccino -- but the goal is still fine, silky microfoam, not more volume of coarse foam.

The risk with a longer stretch is overshooting: aerate too long or too aggressively and you end up with excess foam you''ll then have to fold back into the milk during texturing, or worse, foam so coarse it never fully integrates and shows up as visible bubbles once poured.

The target is a longer but still gentle stretch -- extending the time spent near the surface without increasing the aggressiveness of it, so you get a proportionally larger volume of fine, silky milk rather than simply more of the same coarse foam a rushed cappuccino steam would produce.'
  WHEN 'latte-ch3' THEN 'A heart is the first pour-art shape most people learn, and it comes down to three parts: pitcher height, a steady base pour, and a finishing push through the center.

You start pouring from higher above the cup, letting the milk sink beneath the crema and fill the base of the drink without disturbing the surface. As the cup nears full, you lower the pitcher close to the surface and begin pouring more directly -- this is where the visible white circle starts forming on top of the crema.

The "wiggle-free" part matters: a heart needs a clean, steady circular pour with no side-to-side motion, unlike a rosetta which relies on deliberate wiggling. Once the white circle is roughly the size you want, a fast push of milk directly through its center, while pulling the pitcher up and away, draws that circle into the pointed heart shape.'
  WHEN 'latte-ch4' THEN 'A rosetta is built from the same base pour as a heart, but instead of a clean, steady stream, you introduce a controlled side-to-side wag of the pitcher as you pour, which creates the layered "leaves" that give a rosetta its fern-like appearance.

The wag needs to be rhythmic and consistent -- each pass should be roughly the same width and speed as the last, since uneven wagging produces leaves that look mismatched in size, which is one of the most common ways a rosetta collapses into a messy shape.

As with a heart, the rosetta finishes with a pull-through: after wagging your way most of the way across the cup, you draw the pitcher back through the center of the pattern in a straight line, which is what gives the leaves their defining central stem.'
  WHEN 'latte-ch5' THEN 'A tulip builds multiple distinct shapes by pausing and restarting the pour in stages, rather than one continuous motion the way a heart or rosetta uses. Each pause-and-pour creates one "petal," pushed slightly forward by the next pour''s momentum, which is what creates the stacked, layered look.

Because it''s built from several separate pours rather than one continuous one, a tulip demands more precise pour control than either the heart or rosetta -- each individual petal pour needs to land at a consistent height and volume, or the layers end up uneven in size.

The technique that separates a genuine tulip from a wobbly attempt is really about pour speed control between the pauses, not the pauses themselves -- a controlled, consistent restart each time, rather than the pauses varying in how abruptly the pour resumes.'
  WHEN 'flat-white-ch1' THEN 'A flat white sits between a cappuccino and a latte, but it isn''t simply "a latte with less foam." It uses a tighter milk texture than either drink and typically a higher ratio of espresso to milk than a latte, making it a genuinely more espresso-forward drink.

The name itself points at the intent: "flat" refers to the thin, barely-there foam layer -- present, but nowhere near a cappuccino''s substantial cap -- and the overall texture is meant to feel smoother and denser than a latte''s lighter, airier microfoam.

Because the espresso ratio is higher relative to milk, the coffee flavor comes through more directly than in a latte of the same size, while the tighter milk texture still gives it a rounder, softer mouthfeel than a straight espresso or a cappuccino''s more textured foam.'
  WHEN 'flat-white-ch2' THEN 'Micro-texturing for a flat white pushes further than a latte''s already-fine microfoam -- the goal is a texture so fine it''s nearly imperceptible as separate foam, integrating almost completely into the milk itself.

This takes a shorter, gentler stretch phase than either a cappuccino or latte, since even a small amount of coarse aeration will be more noticeable in a drink built around a barely-there foam layer. Any visible bubbles undermine the whole point of the style.

Getting this right is less about a special technique and more about restraint -- a shorter aeration window than you''d use for other milk drinks, immediately followed by a longer texturing phase to fully integrate whatever small amount of air you did introduce into a dense, velvety consistency.'
  WHEN 'flat-white-ch3' THEN 'Many flat whites are built on a ristretto -- a shorter, more concentrated shot pulled with less water than a standard espresso -- rather than a full standard shot, though this varies by cafe and isn''t a strict requirement of the style.

A ristretto extracts a smaller volume from the same dose, generally emphasizing sweetness and body while pulling back some of the bitterness that comes later in a standard extraction. In a drink with a high milk-to-espresso ratio relative to its small size, that concentration helps the coffee still come through clearly.

Using a standard shot instead isn''t wrong, but it does shift the balance -- a slightly more diluted, less concentrated coffee flavor against the same amount of milk, which some drinkers prefer and others find closer to a small latte than a true flat white.'
  WHEN 'flat-white-ch4' THEN 'Pouring a flat white means adapting your usual latte pour technique to a drink with much less foam to work with -- there simply isn''t enough foam volume to build the same large, elaborate shapes a latte''s thicker cap allows.

The pour still starts from height to let milk settle beneath the crema, but the finishing phase -- where a latte pour would build a heart or rosetta from its foam layer -- needs to be scaled down considerably, since a flat white''s thin foam layer gives you a much smaller canvas to work with.

Many flat whites are finished with a simple, smaller design or just a clean white dot or short heart rather than a full rosetta or tulip, not because the technique is different in principle, but because there genuinely isn''t enough foam volume to build a larger pattern without it collapsing.'
  WHEN 'mocha-ch1' THEN 'A mocha balances three components -- chocolate, espresso, and steamed milk -- and getting that balance wrong in either direction is the most common way a mocha goes wrong. Too much chocolate and the espresso disappears entirely, leaving something closer to hot chocolate with a coffee aftertaste. Too little, and you''re left with a watered-down cocoa flavor that doesn''t taste like much of anything.

The coffee needs to remain genuinely present in a well-made mocha, not just a nominal ingredient. This usually means using a real, full-strength shot rather than a weaker one, since the chocolate and milk both have real flavor weight that a diluted shot won''t stand up against.

Getting the ratio right is less about a fixed formula and more about tasting as you build it -- chocolate products vary enough in sweetness and intensity that the "right" amount for one brand or syrup can be too much or too little for another.'
  WHEN 'mocha-ch2' THEN 'The chocolate base for a mocha is usually either a cocoa powder mixed into a paste, or a pre-made chocolate syrup, and the two behave differently. Cocoa-based mixes tend to give a more intense, slightly bitter chocolate character that needs real sweetening to balance, while syrups are usually already sweetened and integrate more easily but can taste more one-dimensional.

Sweetness level is a real decision point, not an afterthought -- a chocolate base that''s too sweet will fight with espresso''s natural bitterness in an unpleasant way, while one that''s not sweet enough can taste flat or overly bitter once combined with a real shot.

How much to use relative to your shot depends heavily on which base you''re using and its concentration, which is why tasting and adjusting in small increments matters more here than following a single fixed ratio across every chocolate product.'
  WHEN 'mocha-ch3' THEN 'The order you build a mocha in changes how well the chocolate actually integrates with the espresso, rather than just sitting as a separate layer. A common approach is combining the chocolate base directly with the fresh shot first -- while it''s still hot -- so the two dissolve and blend together before the milk is ever added.

Adding chocolate after the milk, or pouring milk directly onto an unmixed shot and chocolate sitting at the bottom, risks the chocolate staying partially unmixed at the bottom of the cup, giving an inconsistent flavor from first sip to last rather than an evenly blended drink throughout.

This is a small step, but it''s one of the more common reasons a mocha tastes uneven -- sweet and chocolatey at the bottom, thin and coffee-forward at the top -- despite using a reasonable ratio of all three components.'
  WHEN 'mocha-ch4' THEN 'Whipped cream, chocolate drizzle, and other mocha finishes are genuinely optional, not a required part of the drink -- and whether to include them is really a question of what kind of drink you''re going for, not a step to always follow by default.

A finished mocha with whipped cream adds a real textural contrast and visual appeal, but it also changes how the drink is experienced -- sipped through cream rather than tasted directly, which mutes some of the espresso and chocolate balance underneath until the cream is gone or stirred in.

For a mocha meant to showcase the actual coffee-chocolate balance more directly, skipping the extra toppings entirely is a reasonable, deliberate choice -- not a lesser version of the drink, just a different one that lets the base three components speak for themselves.'
  WHEN 'americano-ch1' THEN 'An americano is espresso diluted with hot water, but the amount of water you add is a real decision, not an afterthought -- it''s what separates a well-balanced americano from something that tastes like weak, over-diluted coffee.

Too much water and the espresso''s body and flavor thin out until there''s barely anything distinguishing it from a mediocre drip coffee. Too little, and it stays closer to a short, harsh espresso than the smoother, more approachable drink an americano is meant to be.

Done right, an americano keeps real body and crema-derived flavor while being genuinely more approachable to drink than a straight shot -- which is the whole point of the style, not simply "diluted espresso" done carelessly.'
  WHEN 'americano-ch2' THEN 'Whether you pour espresso into hot water or hot water into espresso genuinely changes the resulting drink, even though the final ratio of coffee to water ends up the same either way.

Pouring espresso into water tends to preserve more of the crema on top, since it isn''t disrupted by water crashing down onto it, giving a slightly different mouthfeel and appearance. Pouring water directly onto the espresso disrupts and breaks down the crema, integrating it more thoroughly into the drink but losing that distinct top layer.

Neither order is objectively correct -- it''s a real stylistic choice that changes texture and presentation, and worth trying both ways with the same beans to notice the difference for yourself rather than assuming it doesn''t matter.'
  WHEN 'americano-ch3' THEN 'An iced americano needs real adjustment, not just pouring a hot americano over ice -- since the ice itself is going to melt and add more dilution on top of whatever water was already used, a straight hot recipe poured over ice often ends up tasting thin and watered-down once the ice has done its work.

A common fix is using less added hot water than you would for a hot americano, effectively building a slightly more concentrated base, with the ice supplying the rest of the dilution as it melts over the course of drinking it.

Timing also matters more for iced versions -- a drink built correctly but left to sit for a long time will keep diluting as more ice melts, so an iced americano is genuinely a "drink relatively soon" beverage in a way a hot one, sitting at a stable temperature, isn''t.'
  WHEN 'cold-brew-ch1' THEN 'Cold brew ratios differ meaningfully depending on whether you''re making a concentrate meant to be diluted later, or a ready-to-drink batch meant to be consumed as-is. A concentrate is steeped much stronger, often close to 1:4 or 1:5 coffee to water by weight, expecting to be cut with water or milk before drinking. A ready-to-drink batch uses far more water relative to coffee, since nothing further will be added.

Cold brew also needs a noticeably coarser grind than you''d use for a hot brewing method. Fine grounds in a long, cold steep tend to over-extract and turn muddy or bitter, and can also make filtering the finished batch far more difficult, clogging filters with fine sediment.

Getting the ratio wrong in either direction shows up clearly: too little coffee for the water gives a thin, weak batch no amount of steeping time will fix; too much for a ready-to-drink batch gives something overwhelmingly strong and better suited as a concentrate instead.'
  WHEN 'cold-brew-ch2' THEN 'Cold brew typically steeps for 12 to 24 hours, and unlike hot brewing where a longer extraction generally means a stronger, more bitter cup, cold brew''s relationship between time and strength is different -- because the process is happening at cold temperatures, extraction is inherently slower and gentler across the board.

Steeping even longer than the recommended window doesn''t function as the same lever "brew it hotter and longer" would for a hot method -- past a certain point, additional time mostly just continues slowly extracting without proportionally increasing strength the way heat-driven extraction would, and can eventually start pulling out less pleasant, overly vegetal notes rather than more desirable ones.

Temperature matters too, not just as "cold vs. hot" but within cold brewing itself -- steeping in the refrigerator versus at room temperature changes how quickly extraction happens, with room-temperature steeps generally needing less total time than a fridge steep to reach a similar strength.'
  WHEN 'cold-brew-ch3' THEN 'How you filter a finished cold brew batch changes its final clarity and body meaningfully. Paper filtration gives the clearest, cleanest result, removing essentially all fine sediment and oils, similar to how paper filters work for hot pour-over.

Cloth filtration sits in between -- clearer than a coarse mesh but not as clean as paper, letting through a small amount of fine particulate and some oils, giving slightly more body than a paper-filtered batch.

Mesh or metal filtration is the fastest and coarsest option, letting through the most sediment and oils, giving the fullest body of the three methods but requiring the most patience for sediment to settle out of the final drink, or accepting a slightly gritty result. None of these is strictly "correct" -- it''s a real tradeoff between clarity, speed, and body that''s worth choosing deliberately rather than defaulting to whatever''s most convenient.'
  WHEN 'cold-brew-ch4' THEN 'A single cold brew concentrate batch can scale into multiple different drinks, which is a big part of why concentrate-style brewing is popular for anyone making more than a single cup at a time. The same base batch becomes an iced black coffee, a milk-based cold brew, or a stronger "shot"-style pour, just by changing the dilution ratio at the point of serving.

Dilution ratios need real testing per batch, since concentrate strength varies depending on your original steep ratio -- a common starting point is diluting roughly 1:1 with water or milk, then adjusting from there based on taste, rather than assuming a fixed ratio works across every concentrate strength.

Concentrate also has a genuinely longer shelf life than a diluted, ready-to-drink batch, since it hasn''t yet been mixed with the water or milk that would otherwise start diluting its flavor and inviting faster spoilage -- typically lasting one to two weeks refrigerated, versus just a few days once diluted.'
  WHEN 'turkish-ch1' THEN 'Turkish coffee needs a grind finer than espresso -- closer to a fine powder than the somewhat coarser grind espresso uses -- because the coffee itself is never filtered out of the final drink. Instead, the grounds settle at the bottom of the cup after brewing and serving.

A grind that''s too coarse won''t settle properly and will leave gritty, unpleasant sediment mixed throughout the drink rather than cleanly at the bottom. It also won''t extract the same way the traditional method depends on, since the whole brewing process is built around that very fine grind interacting with slowly heated water.

Getting a true Turkish-coffee-fine grind at home is genuinely difficult with many standard grinders, which is why a dedicated Turkish/Greek coffee grinder, capable of a finer setting than most all-purpose grinders offer, is often recommended for anyone brewing this style regularly.'
  WHEN 'turkish-ch2' THEN 'Kaymak, the foam cap on well-made Turkish coffee, is built through a slow-heat technique rather than any kind of aeration or whisking. As the finely-ground coffee and water heat gradually in a cezve, foam naturally begins rising to the surface well before the mixture ever reaches a boil.

Rushing the heat defeats this entirely -- if the water heats too quickly, it reaches a rolling boil before that foam has had time to properly develop and rise, and the traditional foam cap either never fully forms or gets disrupted immediately once boiling actually starts.

This is why Turkish coffee is traditionally brewed over low, patient heat rather than anything fast -- the technique depends on giving the foam time to develop slowly, which a rushed high-heat approach simply doesn''t allow.'
  WHEN 'turkish-ch3' THEN 'Genuine Turkish coffee brewing avoids ever reaching a full rolling boil, instead bringing the mixture just to the point of foaming -- where bubbles begin rising and the foam starts to crest -- then removing it from heat before it actually boils over.

This foaming point is often reached multiple times across a single brew, not just once: the cezve is removed from heat right as foam begins to rise, some foam is spooned out into the serving cup, then the remainder is returned to heat to bring it to the foaming point again, repeating this a few times before the final pour.

A full boil, by contrast, is generally avoided because it disrupts the foam structure that''s taken time to build and can make the final texture harsher, closer to simply boiled coffee grounds in water than the deliberately controlled Turkish method.'
  WHEN 'turkish-ch4' THEN 'Serving Turkish coffee properly involves settling and etiquette as much as brewing technique. After brewing, the coffee is typically left to sit for a short moment before drinking, allowing the fine grounds to settle further toward the bottom of the cup rather than being disturbed immediately.

When pouring from the cezve into serving cups, foam is traditionally distributed first, spooned or poured evenly across each cup before the remaining liquid coffee is added -- ensuring every cup gets a fair share of the prized foam cap rather than one cup getting most of it and others getting none.

Drinking etiquette also plays a role: Turkish coffee is meant to be sipped slowly, partly out of tradition and partly for practical reasons, since drinking too quickly or too close to the bottom of the cup means disturbing and drinking the settled grounds, which is generally avoided.'
  WHEN 'vietnamese-ch1' THEN 'A phin filter brews through a simple but deliberate sequence: a small bloom with a splash of hot water to let the grounds swell and begin releasing gas, followed by filling the rest of the chamber, then a slow, patient drip through the metal filter into the cup below.

The bloom matters here just as it does in pour-over brewing -- skipping it and filling the chamber all at once tends to produce uneven extraction, since the dry grounds haven''t had a moment to expand and settle before the full weight of water arrives.

Drip speed is controlled largely by how tightly the phin''s press disc is set against the grounds -- pressed too loose and water rushes through too fast for a full extraction; pressed too tight and it can stop dripping almost entirely. Getting a slow, steady drip over several minutes is the real goal, not simply water passing through as fast as possible.'
  WHEN 'vietnamese-ch2' THEN 'Condensed milk is a defining ingredient of Vietnamese coffee, and how much you use is a real balancing act against a typically strong, dark roast base -- too little and the drink stays harshly bitter with little sweetness to round it out; too much and the coffee flavor gets buried entirely under sugar.

Hot versions (ca phe nong) and iced versions (ca phe da) generally call for somewhat different condensed milk ratios, since the iced version will experience further dilution as ice melts over the course of drinking it, similar to the same consideration in an iced americano.

The strong, typically dark-roasted coffee base used in this style is itself a deliberate choice matched to condensed milk''s sweetness -- a lighter, more delicate roast would likely get completely overwhelmed by the amount of condensed milk this style typically calls for.'
  WHEN 'vietnamese-ch3' THEN 'Serving Vietnamese coffee hot (ca phe nong) versus over ice (ca phe da) calls for real adjustments beyond just adding ice at the end. For the iced version, brewing directly over ice, or brewing normally and then pouring over a full glass of ice, means accounting for the dilution that ice will add as it melts.

Drip time is also worth adjusting for the iced version -- since the coffee will be diluted further by melting ice, brewing a slightly more concentrated result through the phin (a bit less water, or a finer grind for a slower drip) helps the final iced drink avoid tasting washed out once the ice has done its work.

The hot version, by contrast, doesn''t face this same dilution concern, so it''s brewed to be enjoyed at roughly the strength it comes out of the phin at, without needing to compensate for anything melting into it afterward.'
  WHEN 'moka-pot-ch1' THEN 'A moka pot works through steam pressure, not the much higher pressure a real espresso machine generates. As water in the bottom chamber heats, building steam pressure pushes it up through a bed of grounds in the middle basket and into the top chamber as brewed coffee.

Because the pressure involved is meaningfully lower than true espresso pressure, a moka pot doesn''t produce genuine crema or the same concentrated extraction espresso does, despite a common misconception that it''s "stovetop espresso." What it does produce is a strong, rich coffee with real body, distinct from both drip coffee and true espresso.

Understanding this distinction matters practically: trying to treat moka pot coffee as if it were espresso (using it as the base for milk drinks expecting espresso-level concentration, for instance) often disappoints, when appreciating it as its own genuinely good, distinct brewing method tends to go much better.'
  WHEN 'moka-pot-ch2' THEN 'The classic burnt, bitter moka pot cup usually traces back to two specific mistakes: a grind that''s too fine, and overpacking the basket. Both cause water to struggle to pass through evenly, extending contact time well past what the method is designed for and pulling out excessive bitterness.

A grind noticeably coarser than espresso, closer to a fine drip grind, generally works better for a moka pot -- fine enough for real extraction, but not so fine it chokes the flow the way an espresso-fine grind would in a system not designed for espresso-level pressure.

Basket fill level matters just as much as grind size: the grounds should sit level, filled but not aggressively packed or tamped down. Overpacking, especially combined with too fine a grind, is one of the most reliable ways to produce the harsh, over-extracted result moka pots are unfairly stereotyped for.'
  WHEN 'moka-pot-ch3' THEN 'Managing heat throughout a moka pot brew, not just at the start, matters for avoiding a scorched, bitter final result. Starting on too high a heat can cause the water to boil too aggressively once pressure builds, pushing coffee through too fast for proper extraction and risking scorching the grounds as the very last of the water passes through.

A common technique is starting on medium heat, then reducing it further once brewing sound (a hissing or gurgling) begins, which slows the final stages of the brew and helps avoid that scorched, burnt taste that comes from the last bit of water forcing through an already mostly-dry, hot puck of grounds.

Removing the pot from heat promptly once brewing sound changes to a sputtering, mostly-empty sound is the other half of this -- letting it continue on high heat after that point mostly just scorches whatever coffee remains without meaningfully adding more brewed volume.'
  WHEN 'affogato-ch1' THEN 'An affogato depends on timing more than almost any other coffee drink -- the shot needs to be poured over the ice cream while it''s genuinely hot, right off the machine, since the whole appeal of the drink comes from that immediate contrast between hot espresso and cold ice cream.

A shot that''s sat even a few minutes loses enough heat that the contrast softens considerably, and the visual and textural effect -- watching the ice cream begin to melt slightly under the hot pour -- doesn''t happen the same way with a lukewarm shot.

Because of this, an affogato is built in reverse order from what you might expect: the ice cream goes into the glass first and waits, while the espresso shot is pulled last, right before serving, rather than having the ice cream sit out waiting for a shot that hasn''t been pulled yet.'
  WHEN 'affogato-ch2' THEN 'The glass and ice cream you choose both change how an affogato actually eats and melts, not just how it looks. A smaller glass concentrates the hot shot against a smaller surface area of ice cream, causing faster melting and a more integrated, drinkable result sooner. A wider glass or bowl spreads the same shot across more ice cream, melting it more slowly and keeping distinct pockets of solid ice cream and pooled coffee for longer.

Ice cream density matters too -- a denser, higher-fat ice cream resists melting longer than a lighter, airier one, meaning the same hot shot poured over each will produce a noticeably different eating experience even with identical technique otherwise.

Neither approach is more correct than the other; it''s a real choice between a quickly-melting, more drink-like affogato versus a slower one that stays more distinctly "ice cream with coffee poured over it" for longer, and worth choosing deliberately based on which experience you''re actually going for.'
  WHEN 'sensory-cupping-ch1' THEN 'Cupping is a standardized coffee-tasting method that lets professionals compare different coffees fairly against each other, controlling for as many variables as possible so differences in the cup reflect real differences in the coffee, not inconsistent brewing.

This matters because ordinary brewing -- pour-over, espresso, drip -- introduces real variation from brewer skill, equipment, and technique, all of which can mask or exaggerate a coffee''s actual qualities. Cupping strips much of that away with a simple, consistent method: a fixed grind, a fixed water ratio, steeped directly in an open bowl rather than filtered through any brewing device.

What cupping is actually measuring is the coffee itself, as directly and consistently as possible -- its aroma, flavor, body, acidity, and aftertaste -- in a format that lets you compare multiple coffees side by side under identical conditions, rather than evaluating just one coffee brewed however you happen to brew it that day.'
  WHEN 'sensory-cupping-ch2' THEN 'Setting up a proper cupping table starts with a fixed, consistent grind and water ratio applied identically across every coffee being compared -- commonly a medium-coarse grind with a ratio around 1:18 or similar (coffee to water by weight), though exact standards vary by organization.

Each coffee gets its own bowl or cup, with dry grounds first smelled on their own (the "dry aroma"), before hot water at a consistent temperature -- typically just off the boil -- is poured directly over the grounds in each bowl, all as close to simultaneously as practical.

Timing matters as much as ratio: every bowl needs to steep for the same duration before the next step (breaking the crust, covered in the next lesson), since inconsistent steep times between bowls would reintroduce exactly the kind of uncontrolled variable cupping is designed to eliminate -- whether you''re comparing two coffees or ten.'
  WHEN 'sensory-cupping-ch3' THEN 'Aroma assessment in cupping happens in two distinct stages: dry aroma, smelled from the ground coffee before any water touches it, and wet aroma (or "crust" aroma), smelled once hot water has been poured and a crust of grounds has formed on top of each bowl.

Breaking the crust is a specific step: after steeping, a spoon is used to gently push the floating crust of grounds aside while leaning in close to smell what''s released in that moment -- often the most aromatically intense point in the entire cupping process, since it''s releasing aromatics that had been trapped just beneath that crust.

Aroma comes first in a cupping sequence, before any tasting begins, because it''s evaluating something genuinely different from flavor -- and because aromatics fade and change over time, assessing them early, at both the dry and wet stages, captures qualities that would be lost or diminished by the time tasting begins.'
  WHEN 'sensory-cupping-ch4' THEN 'Acidity in coffee tasting refers to a bright, lively quality -- often described in terms of specific fruits like citrus or apple -- and is a genuinely desirable characteristic in most specialty coffee, distinct from sourness, which reads as an unpleasant, often sharp or vinegary flaw usually caused by underextraction.

Learning to tell these apart takes real practice, since both can register as a similar initial sharpness on the tongue. The difference tends to show up in how the sensation resolves: pleasant acidity tends to feel bright and then fade cleanly, often described as juicy or crisp, while sourness tends to linger unpleasantly or feel flat and one-dimensional rather than complex.

Body refers to the weight and texture of the coffee in your mouth -- how heavy or light, thin or syrupy it feels -- and thin, watery body is often (though not always) a sign of underextraction, where not enough of the coffee''s soluble compounds made it into the cup to give it real weight and mouthfeel.'
  WHEN 'sensory-cupping-ch5' THEN 'Aftertaste and finish describe what lingers in your mouth after swallowing (or spitting, in professional cupping) the coffee -- and there''s a real, describable difference between a clean finish that fades pleasantly and a lingering one that overstays, whether pleasantly or not.

A clean finish typically resolves within a reasonable window, leaving a pleasant impression without demanding continued attention. A lingering finish persists much longer, which can be a genuinely positive quality if what lingers is pleasant (a coffee praised for a "long, chocolatey finish," for instance) or a negative one if what lingers is bitter, harsh, or otherwise unpleasant.

Building real vocabulary for describing aftertaste -- reaching for specific comparisons like chocolate, dried fruit, or nuttiness rather than just "good" or "bad" -- is a skill that develops with deliberate practice, tasting many different coffees side by side and consciously naming what you notice rather than passively drinking.'
  WHEN 'sensory-cupping-ch6' THEN 'A cupping scoresheet breaks a coffee down into individual categories -- aroma, acidity, body, flavor, aftertaste, and often a few others depending on the specific scoring system used -- each scored somewhat independently before being combined into an overall total.

Scoring individually, rather than just giving one overall gut impression, forces more careful, deliberate attention to each specific quality, and makes it possible to identify precisely where one coffee outperforms or underperforms another, rather than just knowing you preferred one over the other without being able to say exactly why.

Using a scoresheet across multiple coffees side by side, tasted in the same session under the same conditions, is what makes real comparison possible -- a coffee scored on its own, on a different day, under different conditions, isn''t nearly as reliably comparable as several coffees scored together, back to back, in one sitting.'
  WHEN 'cafe-management-ch1' THEN 'Costing a menu item means accounting for real ingredient, labor, and overhead costs behind that specific drink -- not just the wholesale price of the coffee beans themselves, which is often a smaller piece of the true cost than people expect.

Ingredient cost includes everything that physically goes into the cup: coffee, milk, syrups, the cup and lid itself. Labor cost accounts for the barista''s time to make it, proportioned across however many drinks they can realistically produce in an hour. Overhead spreads a share of rent, utilities, equipment costs, and other fixed expenses across every drink sold, since those costs exist whether or not any particular drink gets made.

Missing any of these three categories when costing a menu item is a common, genuinely expensive mistake -- a drink can look profitable when you only account for the beans, while actually losing money once labor and overhead are honestly factored in.'
  WHEN 'cafe-management-ch2' THEN 'Pricing for margin means setting menu prices that genuinely cover your full real cost (ingredients, labor, overhead) and leave real profit on top -- not just pricing based on what competitors charge or what feels reasonable without doing the actual cost math first.

A common approach is calculating your true cost per drink, then applying a target margin percentage on top to arrive at a price -- for instance, if a drink genuinely costs $2 to make once labor and overhead are included, pricing it to achieve a 70% margin means charging closer to $6.67, not simply doubling the ingredient cost alone.

Pricing purely by matching competitors, without first knowing your own real costs, risks setting a price that looks reasonable in the market but doesn''t actually cover what it costs you to make that drink -- a mistake that only becomes visible once you look at real numbers rather than gut instinct.'
  WHEN 'cafe-management-ch3' THEN 'Staffing a shift well means matching staff levels to real, observed demand patterns -- busy mornings, quieter afternoons, weekend surges -- rather than guessing or defaulting to the same staffing level every day regardless of actual traffic.

Overstaffing has a real, measurable cost: paying wages for staff hours that demand doesn''t actually require, which adds up significantly over weeks and months even if any single overstaffed shift doesn''t feel like a big deal in isolation.

Understaffing has its own real cost too, just harder to see directly on a labor report -- slower service, frustrated customers, and staff burnout from being consistently stretched too thin, all of which can cost more in lost future business than the wages saved by cutting a shift too thin in the moment.'
  WHEN 'cafe-management-ch4' THEN 'Training baristas consistently means building a real, repeatable training process, so drink quality doesn''t end up depending on which specific barista happens to be working a given shift -- a genuine and common problem in cafes without a deliberate training system in place.

Without consistent training, each barista tends to develop their own habits and shortcuts over time, which can drift meaningfully from your actual standards, especially for judgment calls like exact steaming technique or when a shot counts as "good enough" to serve versus needing to be re-pulled.

A real training process usually includes written standards (exact ratios, timing, technique descriptions) combined with hands-on practice and feedback, rather than relying purely on informal observation or a new hire just watching an experienced staff member for a shift or two and picking it up as they go.'
  WHEN 'cafe-management-ch5' THEN 'Tracking inventory and waste properly means ordering based on real, observed usage patterns rather than habit or guesswork -- if you''ve always ordered the same amount of a particular syrup or milk regardless of how much actually gets used versus wasted, you''re very likely over- or under-ordering without realizing it.

Waste tracking specifically -- recording what gets thrown out and why (expired, spilled, made incorrectly and remade) -- reveals real, actionable patterns that simple sales data alone won''t show. A high-waste item might be selling fine but also getting wasted at a rate that''s quietly eating into its actual profit margin.

Regular physical counts, compared against what your sales and waste records suggest you should have on hand, catch discrepancies early -- whether from measurement drift, unrecorded waste, or other issues -- before they compound into a much larger, harder-to-diagnose inventory problem down the line.'
  WHEN 'cafe-management-ch6' THEN 'Designing a menu means genuinely balancing variety against what your team can actually execute consistently, especially during a real rush -- an extensive, ambitious menu that looks impressive on paper can become a serious liability the moment real volume hits and every item needs to come out correctly and quickly.

Each additional menu item adds real complexity: more ingredients to stock and track, more techniques staff need to stay sharp on, and more decision points that can slow down both staff and customers during busy periods. A shorter, well-executed menu often outperforms a longer one that stretches your team too thin to execute any single item consistently well.

This doesn''t mean menus should never be ambitious -- it means ambition needs to be weighed honestly against real operational capacity, ideally tested during actual rush conditions before committing to a permanent menu, not just planned around a quiet afternoon when execution pressure is genuinely lower.'
  WHEN 'cafe-management-ch7' THEN 'Managing a real rush comes down largely to workflow and station design decided well before the rush ever hits, not improvised decisions made in the moment once a line has already formed and pressure is high.

A well-designed station layout minimizes unnecessary movement -- ingredients, tools, and equipment positioned so a barista can execute the most common drinks without excessive reaching, walking, or backtracking, which adds up to real time lost across dozens of drinks during a genuine rush.

Clear roles matter just as much as physical layout when multiple staff are working together: who''s taking orders, who''s on espresso, who''s on milk steaming and assembly, decided in advance rather than improvised in real time, prevents the kind of confusion and duplicated or dropped steps that slow a whole team down exactly when speed matters most.'
  WHEN 'cafe-management-ch8' THEN 'Customer experience often comes down to small, genuinely repeatable things rather than any single grand gesture -- remembering a regular''s usual order, a consistent greeting, actually looking up and acknowledging someone waiting rather than staying heads-down the entire time, none of which require extra ingredients or significant extra time, but all of which real customers notice and remember.

Consistency in these small things matters more than any single exceptional interaction -- a customer who''s treated well most visits but occasionally ignored or rushed through tends to remember the inconsistency more than either extreme individually, since it makes the experience feel unpredictable rather than reliably good.

These habits are also genuinely trainable, the same way drink-making technique is -- building small customer-facing habits into your actual training process, not just hoping staff naturally pick them up, is what makes them consistent across an entire team rather than dependent on which individual happens to have a naturally warm personality that day.'
  WHEN 'cafe-management-ch9' THEN 'Running a cafe well means regularly checking a handful of real, meaningful numbers -- not vanity metrics like total transaction count alone, which can look healthy while actual profitability quietly suffers underneath.

Real numbers worth checking weekly include actual margin per drink category (not just revenue), labor cost as a percentage of sales (a common target range exists, and drifting well outside it signals a real problem), and waste rate by item, connecting directly back to the inventory tracking covered earlier in this course.

The habit of checking these numbers regularly, not just occasionally or only when something already feels wrong, is what actually makes them useful -- a problem caught early, from a number that''s started drifting, is far easier and cheaper to correct than the same problem discovered months later once it''s had time to compound into something much larger.'
  ELSE content
END WHERE id IN ('cappuccino-ch1', 'cappuccino-ch2', 'cappuccino-ch3', 'cappuccino-ch4', 'cappuccino-ch5', 'latte-ch1', 'latte-ch2', 'latte-ch3', 'latte-ch4', 'latte-ch5', 'flat-white-ch1', 'flat-white-ch2', 'flat-white-ch3', 'flat-white-ch4', 'mocha-ch1', 'mocha-ch2', 'mocha-ch3', 'mocha-ch4', 'americano-ch1', 'americano-ch2', 'americano-ch3', 'cold-brew-ch1', 'cold-brew-ch2', 'cold-brew-ch3', 'cold-brew-ch4', 'turkish-ch1', 'turkish-ch2', 'turkish-ch3', 'turkish-ch4', 'vietnamese-ch1', 'vietnamese-ch2', 'vietnamese-ch3', 'moka-pot-ch1', 'moka-pot-ch2', 'moka-pot-ch3', 'affogato-ch1', 'affogato-ch2', 'sensory-cupping-ch1', 'sensory-cupping-ch2', 'sensory-cupping-ch3', 'sensory-cupping-ch4', 'sensory-cupping-ch5', 'sensory-cupping-ch6', 'cafe-management-ch1', 'cafe-management-ch2', 'cafe-management-ch3', 'cafe-management-ch4', 'cafe-management-ch5', 'cafe-management-ch6', 'cafe-management-ch7', 'cafe-management-ch8', 'cafe-management-ch9');

UPDATE chapters SET objectives = CASE id
  WHEN 'cappuccino-ch1' THEN ARRAY['Explain what the 1:1:1 ratio actually means in a cappuccino', 'Understand why cup size matters for keeping the ratio honest']
  WHEN 'cappuccino-ch2' THEN ARRAY['Describe what real microfoam looks and feels like versus large-bubble foam', 'Identify the three main variables that control milk texture while steaming']
  WHEN 'cappuccino-ch3' THEN ARRAY['Distinguish between the stretching and texturing phases of steaming milk', 'Explain what goes wrong when either phase is rushed or skipped']
  WHEN 'cappuccino-ch4' THEN ARRAY['Explain why pour height matters more for a cappuccino than a larger drink', 'Understand why a cappuccino''s short pour time leaves little room to correct mistakes']
  WHEN 'cappuccino-ch5' THEN ARRAY['Explain why a cappuccino needs to be served immediately rather than staged ahead', 'Understand what physically happens to the drink if it sits too long']
  WHEN 'latte-ch1' THEN ARRAY['Explain how a latte''s milk ratio differs from a cappuccino''s, and why', 'Understand why a latte''s larger volume allows for pour-art techniques a cappuccino doesn''t']
  WHEN 'latte-ch2' THEN ARRAY['Explain why a latte''s stretching phase runs longer than a cappuccino''s', 'Understand the risk of overshooting the stretch phase']
  WHEN 'latte-ch3' THEN ARRAY['Describe the three stages involved in pouring a heart', 'Explain what distinguishes a heart pour from a rosetta pour']
  WHEN 'latte-ch4' THEN ARRAY['Explain what creates the leaf pattern in a rosetta', 'Identify the most common cause of an uneven or collapsed rosetta']
  WHEN 'latte-ch5' THEN ARRAY['Explain how a tulip''s layered shapes are built compared to a heart or rosetta', 'Understand why pour speed control matters more for a tulip than for simpler shapes']
  WHEN 'flat-white-ch1' THEN ARRAY['Explain what distinguishes a flat white from both a cappuccino and a latte', 'Understand what ''flat'' actually refers to in the name']
  WHEN 'flat-white-ch2' THEN ARRAY['Explain how flat white micro-texturing differs from standard latte foam', 'Understand why restraint during the stretch phase matters more for a flat white']
  WHEN 'flat-white-ch3' THEN ARRAY['Explain what a ristretto shot is and how it differs from a standard shot', 'Understand why concentration matters more in a flat white''s small, milk-heavy format']
  WHEN 'flat-white-ch4' THEN ARRAY['Explain why flat white pour art is typically simpler than latte pour art', 'Understand how the thin foam layer limits what''s achievable during the pour']
  WHEN 'mocha-ch1' THEN ARRAY['Explain the balance problem at the heart of a well-made mocha', 'Understand why shot strength matters more in a mocha than in some other milk drinks']
  WHEN 'mocha-ch2' THEN ARRAY['Compare cocoa-based chocolate bases to pre-made syrups', 'Explain why sweetness level is a real decision, not a default setting']
  WHEN 'mocha-ch3' THEN ARRAY['Explain why mixing chocolate with the fresh shot first matters', 'Identify the common result of getting the build order wrong']
  WHEN 'mocha-ch4' THEN ARRAY['Understand that mocha finishes like whipped cream are optional, not required', 'Explain how added toppings change the drinking experience versus a plain finish']
  WHEN 'americano-ch1' THEN ARRAY['Explain why the amount of water added is a real decision in an americano, not a default', 'Understand the difference between a well-balanced americano and simply diluted espresso']
  WHEN 'americano-ch2' THEN ARRAY['Explain how pour order affects the crema in an americano', 'Understand that this is a real stylistic choice, not a fixed rule']
  WHEN 'americano-ch3' THEN ARRAY['Explain why an iced americano needs a different water ratio than a hot one', 'Understand why ice melt continues to affect the drink over time']
  WHEN 'cold-brew-ch1' THEN ARRAY['Explain the difference between a concentrate ratio and a ready-to-drink ratio', 'Understand why cold brew needs a coarser grind than hot brewing methods']
  WHEN 'cold-brew-ch2' THEN ARRAY['Explain why longer cold brew steep time doesn''t function the same way longer hot brew time does', 'Understand how steeping temperature (fridge vs. room temperature) affects extraction speed']
  WHEN 'cold-brew-ch3' THEN ARRAY['Compare paper, cloth, and mesh filtration for cold brew', 'Understand the real tradeoff between clarity, speed, and body across filtration methods']
  WHEN 'cold-brew-ch4' THEN ARRAY['Explain how a single concentrate batch can become multiple different drinks', 'Understand why concentrate has a longer shelf life than a diluted, ready-to-drink batch']
  WHEN 'turkish-ch1' THEN ARRAY['Explain why Turkish coffee needs an unusually fine grind compared to espresso', 'Understand what happens if the grind is too coarse for this method']
  WHEN 'turkish-ch2' THEN ARRAY['Explain how kaymak (the foam cap) actually forms during brewing', 'Understand why rushing the heat prevents the foam from developing properly']
  WHEN 'turkish-ch3' THEN ARRAY['Explain what ''brewing to the point of foaming'' actually means', 'Understand why the process is repeated across multiple heating cycles rather than done once']
  WHEN 'turkish-ch4' THEN ARRAY['Explain the traditional order of serving foam versus liquid coffee', 'Understand why Turkish coffee is meant to be sipped slowly rather than quickly']
  WHEN 'vietnamese-ch1' THEN ARRAY['Describe the three stages of brewing with a phin filter', 'Explain what controls the drip speed and why it matters']
  WHEN 'vietnamese-ch2' THEN ARRAY['Explain why condensed milk ratio is a real balancing decision, not a fixed amount', 'Understand why hot and iced versions generally use somewhat different ratios']
  WHEN 'vietnamese-ch3' THEN ARRAY['Explain why the iced version needs adjustments the hot version doesn''t', 'Understand how to compensate for ice dilution when brewing ca phe da']
  WHEN 'moka-pot-ch1' THEN ARRAY['Explain why a moka pot isn''t genuine espresso, despite the common comparison', 'Understand what moka pot coffee is actually good at, on its own terms']
  WHEN 'moka-pot-ch2' THEN ARRAY['Identify the two most common causes of a burnt, bitter moka pot cup', 'Explain the correct grind size and fill approach for a moka pot']
  WHEN 'moka-pot-ch3' THEN ARRAY['Explain why heat needs to be managed throughout the brew, not just set once at the start', 'Understand the signs that indicate when to reduce heat or remove the pot entirely']
  WHEN 'affogato-ch1' THEN ARRAY['Explain why shot temperature is so critical to an affogato', 'Understand why the ice cream goes into the glass before the espresso, not after']
  WHEN 'affogato-ch2' THEN ARRAY['Explain how glass size affects how quickly an affogato melts and integrates', 'Understand how ice cream density changes the eating experience']
  WHEN 'sensory-cupping-ch1' THEN ARRAY['Explain what problem cupping solves that ordinary brewing doesn''t', 'Understand what cupping is actually designed to measure']
  WHEN 'sensory-cupping-ch2' THEN ARRAY['List what needs to stay consistent across every bowl in a cupping session', 'Explain why steep timing matters as much as grind and ratio']
  WHEN 'sensory-cupping-ch3' THEN ARRAY['Distinguish between dry aroma and wet (crust) aroma in cupping', 'Explain why breaking the crust is often the most aromatically intense moment']
  WHEN 'sensory-cupping-ch4' THEN ARRAY['Distinguish between desirable acidity and undesirable sourness', 'Explain what body refers to, and what thin body can indicate']
  WHEN 'sensory-cupping-ch5' THEN ARRAY['Explain what distinguishes a clean finish from a lingering one', 'Understand why a lingering finish isn''t automatically a negative quality']
  WHEN 'sensory-cupping-ch6' THEN ARRAY['Explain why cupping uses individual category scores rather than one overall impression', 'Understand why scoring multiple coffees together in one session matters for real comparison']
  WHEN 'cafe-management-ch1' THEN ARRAY['List the three real cost categories behind a single menu item', 'Explain why ingredient cost alone often understates the true cost of a drink']
  WHEN 'cafe-management-ch2' THEN ARRAY['Explain what pricing for margin actually means beyond just matching competitors', 'Understand why knowing your true cost per drink has to come before setting a price']
  WHEN 'cafe-management-ch3' THEN ARRAY['Explain why staffing should be matched to observed demand patterns, not a flat default', 'Understand the real costs of both overstaffing and understaffing']
  WHEN 'cafe-management-ch4' THEN ARRAY['Explain why quality can drift without a consistent training process', 'Understand what a real training process includes beyond informal observation']
  WHEN 'cafe-management-ch5' THEN ARRAY['Explain why inventory ordering should be based on real usage data, not habit', 'Understand what waste tracking reveals that sales data alone doesn''t']
  WHEN 'cafe-management-ch6' THEN ARRAY['Explain the real tradeoff between menu variety and consistent execution', 'Understand why menu decisions should be tested against real rush conditions, not quiet periods']
  WHEN 'cafe-management-ch7' THEN ARRAY['Explain why rush management depends on decisions made before the rush, not during it', 'Understand how station layout and clear staff roles both contribute to handling volume well']
  WHEN 'cafe-management-ch8' THEN ARRAY['Explain why small, repeatable customer touches often matter more than grand gestures', 'Understand why consistency in customer experience matters more than any single exceptional interaction']
  WHEN 'cafe-management-ch9' THEN ARRAY['List real, meaningful numbers worth checking weekly versus vanity metrics', 'Explain why checking these numbers regularly matters more than checking them occasionally']
  ELSE objectives
END WHERE id IN ('cappuccino-ch1', 'cappuccino-ch2', 'cappuccino-ch3', 'cappuccino-ch4', 'cappuccino-ch5', 'latte-ch1', 'latte-ch2', 'latte-ch3', 'latte-ch4', 'latte-ch5', 'flat-white-ch1', 'flat-white-ch2', 'flat-white-ch3', 'flat-white-ch4', 'mocha-ch1', 'mocha-ch2', 'mocha-ch3', 'mocha-ch4', 'americano-ch1', 'americano-ch2', 'americano-ch3', 'cold-brew-ch1', 'cold-brew-ch2', 'cold-brew-ch3', 'cold-brew-ch4', 'turkish-ch1', 'turkish-ch2', 'turkish-ch3', 'turkish-ch4', 'vietnamese-ch1', 'vietnamese-ch2', 'vietnamese-ch3', 'moka-pot-ch1', 'moka-pot-ch2', 'moka-pot-ch3', 'affogato-ch1', 'affogato-ch2', 'sensory-cupping-ch1', 'sensory-cupping-ch2', 'sensory-cupping-ch3', 'sensory-cupping-ch4', 'sensory-cupping-ch5', 'sensory-cupping-ch6', 'cafe-management-ch1', 'cafe-management-ch2', 'cafe-management-ch3', 'cafe-management-ch4', 'cafe-management-ch5', 'cafe-management-ch6', 'cafe-management-ch7', 'cafe-management-ch8', 'cafe-management-ch9');

INSERT INTO quiz_questions (id, chapter_id, number, question, options, correct_index, explanation) VALUES
('cappuccino-ch1-q1', 'cappuccino-ch1', 1, 'Why does a cappuccino need a smaller cup than a latte?', ARRAY['It doesn''t -- any cup size works the same', 'A larger cup would dilute the 1:1:1 ratio into something closer to a latte', 'Smaller cups keep the coffee hotter for longer', 'It''s purely a stylistic tradition with no functional reason'], 1, 'The 1:1:1 ratio only holds in a cup sized for it -- a bigger cup means proportionally more milk, drifting the drink toward latte territory.'),
('cappuccino-ch2-q1', 'cappuccino-ch2', 1, 'What does properly textured microfoam look like?', ARRAY['Large, visible bubbles like shaving cream', 'A tight, glossy texture with barely visible bubbles, closer to wet paint', 'Completely flat with no texture at all', 'A thick, dry foam that holds a spoon upright'], 1, 'Real microfoam is fine and glossy, not the large-bubble froth many people mistake for good foam.'),
('cappuccino-ch3-q1', 'cappuccino-ch3', 1, 'What is the stretching phase of steaming milk primarily responsible for?', ARRAY['Warming the milk to its final temperature', 'Creating the foam volume by introducing air', 'Breaking down large bubbles into fine microfoam', 'Cooling the milk back down'], 1, 'Stretching is where air gets introduced and foam volume is created; texturing afterward refines that foam into something smooth.'),
('cappuccino-ch4-q1', 'cappuccino-ch4', 1, 'Why does pouring a cappuccino require more precision than pouring a latte?', ARRAY['Cappuccino milk is thicker and harder to pour', 'The smaller total volume leaves very little room for error or correction', 'Cappuccinos always use a different pitcher', 'There''s no real difference between the two'], 1, 'With so little total volume, small mistakes in height or timing show up immediately, and there''s little time to correct them mid-pour.'),
('cappuccino-ch5-q1', 'cappuccino-ch5', 1, 'Why can''t a cappuccino be made ahead of time and held for later, the way some other drinks can?', ARRAY['It has no real shelf-life limitation', 'The microfoam breaks down and separates from the liquid within minutes', 'Cappuccinos are always made in large batches', 'Only the temperature is affected, not the texture'], 1, 'The foam structure that defines a cappuccino starts collapsing almost immediately, which is why it has to be built to order.'),
('latte-ch1-q1', 'latte-ch1', 1, 'Why does a latte''s larger milk volume make pour art like hearts and rosettas possible?', ARRAY['Latte milk is a different temperature', 'The larger surface area and volume give real room and time to build a shape during the pour', 'Latte cups are a different shape', 'It has nothing to do with volume'], 1, 'A cappuccino''s small cup and thin margins don''t leave the room a latte''s larger volume provides for actually shaping a pour.'),
('latte-ch2-q1', 'latte-ch2', 1, 'What''s the risk of stretching latte milk too aggressively, even though a longer stretch is needed?', ARRAY['The milk will taste different', 'You end up with coarse foam that won''t fully integrate into a silky texture', 'The milk will cool down too fast', 'There''s no real risk either way'], 1, 'A longer stretch needs to stay gentle -- aggressive aeration produces coarse foam, not the extra volume of silky microfoam a latte actually needs.'),
('latte-ch3-q1', 'latte-ch3', 1, 'What creates the point at the bottom of a heart shape in latte art?', ARRAY['A slow, steady pour with no changes', 'A fast final push of milk directly through the center of the white circle', 'Side-to-side wiggling of the pitcher', 'Adding the foam after the base pour is complete'], 1, 'The heart''s point comes from a deliberate fast push through the center of the circle at the very end of the pour, not from the earlier steady base pour.'),
('latte-ch4-q1', 'latte-ch4', 1, 'What most commonly causes a rosetta''s leaves to look mismatched or collapse?', ARRAY['Pouring too slowly overall', 'An inconsistent wag -- passes that vary in width or speed from each other', 'Using too much foam', 'The cup being the wrong color'], 1, 'Each wag pass needs to be roughly consistent with the last; uneven wagging is what produces mismatched, collapsed-looking leaves.'),
('latte-ch5-q1', 'latte-ch5', 1, 'What technique is most responsible for a clean, evenly-layered tulip?', ARRAY['Pouring as fast as possible the whole time', 'Consistent, controlled pour speed at the restart of each paused pour', 'Using a completely different pitcher shape', 'Never pausing the pour at all'], 1, 'A tulip is built from multiple restarted pours -- consistent control at each restart is what keeps the layered petals even in size.'),
('flat-white-ch1-q1', 'flat-white-ch1', 1, 'What does ''flat'' refer to in the name ''flat white''?', ARRAY['The drink is served without any foam at all', 'The thin, minimal foam layer, much less than a cappuccino''s substantial cap', 'The shape of the cup it''s traditionally served in', 'It has no specific meaning'], 1, '''Flat'' describes the thin foam layer -- present, but far less than a cappuccino''s -- not a complete absence of foam.'),
('flat-white-ch2-q1', 'flat-white-ch2', 1, 'Why does a flat white need an even shorter stretch phase than a latte?', ARRAY['Flat whites use less milk overall', 'Even small amounts of coarse foam are more noticeable in a drink meant to have barely-there texture', 'The espresso shot takes longer to pull', 'There''s no real difference in stretch time needed'], 1, 'A flat white''s whole identity depends on a nearly imperceptible foam layer, so even minor over-aeration stands out more than it would in a latte.'),
('flat-white-ch3-q1', 'flat-white-ch3', 1, 'Why do many flat whites use a ristretto rather than a standard espresso shot?', ARRAY['Ristretto shots take longer to pull', 'The higher concentration helps the coffee flavor stand out despite the milk ratio', 'It''s required by law in specialty coffee', 'There''s no actual difference between the two'], 1, 'A ristretto''s concentration helps coffee flavor come through clearly even against a relatively high proportion of milk.'),
('flat-white-ch4-q1', 'flat-white-ch4', 1, 'Why is latte art on a flat white typically smaller or simpler than on a latte?', ARRAY['Flat whites don''t allow any pour art at all', 'There''s less foam volume overall, leaving a smaller canvas for shapes', 'The cups are a completely different shape', 'There''s no real difference in what''s possible'], 1, 'A flat white''s thin foam layer simply doesn''t provide the volume a latte''s thicker cap does, limiting how large or elaborate a pattern can be.'),
('mocha-ch1-q1', 'mocha-ch1', 1, 'What''s the most common way a mocha''s flavor balance goes wrong?', ARRAY['Using too much milk relative to chocolate', 'Either too much chocolate burying the espresso, or too little leaving a watered-down cocoa taste', 'The temperature being incorrect', 'There''s no real balance to worry about'], 1, 'A mocha''s whole challenge is keeping all three components -- chocolate, espresso, milk -- genuinely present, which is easy to throw off in either direction.'),
('mocha-ch2-q1', 'mocha-ch2', 1, 'How do cocoa-based chocolate mixes typically differ from pre-made chocolate syrups in a mocha?', ARRAY['There''s no meaningful difference between them', 'Cocoa mixes tend to be more intense and less sweet, needing more balancing than pre-sweetened syrups', 'Syrups always taste better', 'Cocoa mixes can''t be used in a mocha at all'], 1, 'Cocoa-based bases are generally more intense and less sweet than pre-made syrups, requiring more deliberate sweetening to balance.'),
('mocha-ch3-q1', 'mocha-ch3', 1, 'What commonly happens if chocolate isn''t properly mixed with the shot before milk is added?', ARRAY['The drink tastes exactly the same either way', 'The chocolate can settle unevenly, leaving an inconsistent flavor from top to bottom of the cup', 'The espresso loses its caffeine', 'The milk won''t steam properly afterward'], 1, 'Chocolate that isn''t mixed into the hot shot first can settle unevenly, giving an inconsistent taste through the drink rather than a well-blended one.'),
('mocha-ch4-q1', 'mocha-ch4', 1, 'How does whipped cream change the experience of drinking a mocha?', ARRAY['It has no real effect on the drink', 'It mutes the direct coffee-chocolate balance until it''s stirred in or gone', 'It makes the espresso taste stronger', 'It''s a required component of every mocha'], 1, 'Whipped cream adds texture and visual appeal but sits between you and the coffee-chocolate balance underneath until it''s mixed in or finished.'),
('americano-ch1-q1', 'americano-ch1', 1, 'What happens if too much water is added to an espresso shot when making an americano?', ARRAY['Nothing changes -- water amount doesn''t matter', 'The body and flavor thin out until it barely resembles a well-made coffee', 'The caffeine content increases', 'The crema becomes thicker'], 1, 'Too much water thins out the body and flavor that a well-made americano is supposed to retain, unlike a careless over-dilution.'),
('americano-ch2-q1', 'americano-ch2', 1, 'What''s the main difference between pouring espresso into water versus water into espresso?', ARRAY['There is no actual difference in the result', 'Espresso into water tends to preserve more crema on top; water into espresso breaks it down', 'Water into espresso always tastes better', 'The caffeine content changes based on order'], 1, 'The pour order genuinely changes what happens to the crema, even though the final coffee-to-water ratio is the same either way.'),
('americano-ch3-q1', 'americano-ch3', 1, 'Why shouldn''t you simply pour a standard hot americano recipe over ice?', ARRAY['Ice doesn''t affect the flavor of coffee at all', 'The melting ice adds further dilution, on top of the water already used, making it taste watered down', 'Hot americanos can''t be served cold under any circumstances', 'It would make the coffee too strong'], 1, 'Melting ice adds its own dilution on top of the water already in the recipe, so a straight hot recipe over ice tends to end up over-diluted.'),
('cold-brew-ch1-q1', 'cold-brew-ch1', 1, 'Why does cold brew typically need a coarser grind than hot brewing methods?', ARRAY['Coarse grounds brew faster', 'A fine grind in a long cold steep tends to over-extract and can clog filters with sediment', 'Grind size doesn''t actually matter for cold brew', 'Coarse grounds have more caffeine'], 1, 'The long steep time makes fine grounds prone to over-extraction and difficult filtration, unlike the shorter contact times of hot brewing.'),
('cold-brew-ch2-q1', 'cold-brew-ch2', 1, 'Why doesn''t steeping cold brew for much longer than recommended simply make it proportionally stronger, the way brewing hot coffee longer might?', ARRAY['Steep time has zero effect on cold brew strength', 'Cold extraction is inherently slower and gentler, so extra time doesn''t scale strength the same way heat-driven extraction does', 'Cold brew actually gets weaker with more time', 'There''s no real limit to how long you can steep'], 1, 'Cold, slow extraction behaves differently than heat-driven extraction -- past a point, more time doesn''t proportionally add strength and can introduce less pleasant flavors.'),
('cold-brew-ch3-q1', 'cold-brew-ch3', 1, 'Which filtration method typically gives the clearest, cleanest cold brew result?', ARRAY['Mesh or metal filtration', 'Cloth filtration', 'Paper filtration', 'All three give identical results'], 2, 'Paper filtration removes the most fine sediment and oils, giving the clearest result, at the cost of some body compared to mesh.'),
('cold-brew-ch4-q1', 'cold-brew-ch4', 1, 'Why does cold brew concentrate typically last longer in the fridge than a diluted, ready-to-drink batch?', ARRAY['Concentrate has no real shelf-life advantage', 'It hasn''t yet been mixed with water or milk, which would otherwise speed up flavor loss and spoilage', 'Concentrate is always pasteurized', 'Diluted batches are stored differently'], 1, 'Undiluted concentrate keeps longer because it hasn''t been mixed with the water or milk that speeds up flavor degradation once combined.'),
('turkish-ch1-q1', 'turkish-ch1', 1, 'Why does Turkish coffee require such a fine grind, finer than espresso?', ARRAY['It doesn''t -- any grind size works fine', 'The grounds are never filtered out, so a fine grind is needed for them to settle properly rather than stay gritty throughout', 'Fine grinds brew faster', 'It''s purely a matter of tradition with no functional reason'], 1, 'Since the grounds stay in the final cup rather than being filtered out, a fine grind is what allows them to settle cleanly at the bottom instead of staying suspended throughout.'),
('turkish-ch2-q1', 'turkish-ch2', 1, 'How does kaymak, the traditional foam cap, actually form on Turkish coffee?', ARRAY['By vigorously whisking the coffee before serving', 'Through slow, gradual heating that lets foam rise naturally before the water ever reaches a boil', 'By adding a foaming agent to the mixture', 'It forms only after the coffee has cooled'], 1, 'The foam develops gradually as the water heats slowly -- rushing the heat means it boils before the foam has time to properly form.'),
('turkish-ch3-q1', 'turkish-ch3', 1, 'What does genuine Turkish coffee brewing deliberately avoid?', ARRAY['Using any heat at all', 'Letting the mixture reach a full rolling boil', 'Using a cezve', 'Removing it from heat before it''s ready'], 1, 'The method is built around bringing the coffee just to the point of foaming, multiple times, while deliberately avoiding a full boil that would disrupt the foam.'),
('turkish-ch4-q1', 'turkish-ch4', 1, 'In traditional Turkish coffee service, what happens first when pouring into multiple cups?', ARRAY['All the liquid coffee is poured first, then foam is added last', 'Foam is distributed evenly across cups first, before the remaining coffee is added', 'Only one cup receives the foam', 'Foam and coffee are always mixed together beforehand'], 1, 'Foam is traditionally distributed first so every cup gets a fair share, rather than concentrating it in whichever cup happens to be poured first.'),
('vietnamese-ch1-q1', 'vietnamese-ch1', 1, 'What controls how fast (or slow) a phin filter drips?', ARRAY['The color of the metal filter', 'How tightly the press disc is set against the grounds', 'The temperature of the room', 'It can''t be controlled at all'], 1, 'The press disc''s tightness against the grounds directly controls flow rate -- too loose drips too fast, too tight can stop the drip almost entirely.'),
('vietnamese-ch2-q1', 'vietnamese-ch2', 1, 'Why is Vietnamese coffee typically made with a strong, dark roast rather than a lighter one?', ARRAY['Dark roasts brew faster through a phin filter', 'A lighter roast would likely get overwhelmed by the amount of condensed milk typically used', 'Light roasts aren''t available where this style originated', 'Roast level doesn''t actually matter for this drink'], 1, 'The dark, strong base is matched deliberately to condensed milk''s sweetness -- a more delicate roast wouldn''t stand up to the same ratio.'),
('vietnamese-ch3-q1', 'vietnamese-ch3', 1, 'Why might you brew a more concentrated batch specifically for the iced version of Vietnamese coffee?', ARRAY['Iced coffee always needs less caffeine', 'To compensate for the dilution that will happen as the ice melts', 'The hot version uses a different type of bean entirely', 'There''s no real difference in how the two versions are brewed'], 1, 'Since melting ice will dilute the drink further, brewing a stronger base helps the final iced coffee avoid tasting washed out.'),
('moka-pot-ch1-q1', 'moka-pot-ch1', 1, 'Why doesn''t a moka pot produce true crema the way an espresso machine does?', ARRAY['It uses the wrong type of coffee bean', 'The steam pressure involved is meaningfully lower than true espresso pressure', 'Moka pots are too old-fashioned to produce crema', 'It actually does produce identical crema'], 1, 'Moka pots rely on steam pressure, which is lower than the pressure a real espresso machine generates, so they can''t produce genuine crema.'),
('moka-pot-ch2-q1', 'moka-pot-ch2', 1, 'What are the two most common causes of a burnt, over-extracted moka pot cup?', ARRAY['Using the wrong water source', 'A grind that''s too fine combined with overpacking the basket', 'Brewing at high altitude', 'Using a moka pot that''s too large'], 1, 'Fine grind and overpacking both extend contact time past what the method is designed for, pulling excessive bitterness into the final cup.'),
('moka-pot-ch3-q1', 'moka-pot-ch3', 1, 'Why is it recommended to reduce heat partway through a moka pot brew, rather than keeping it constant?', ARRAY['It has no real effect either way', 'It slows the final stages of extraction, helping avoid scorching the grounds as the last water passes through', 'It makes the coffee brew faster overall', 'Constant heat is actually the correct approach'], 1, 'Reducing heat partway through slows the final push of water, helping avoid the scorched taste that comes from forcing the last water through hot, nearly-dry grounds.'),
('affogato-ch1-q1', 'affogato-ch1', 1, 'Why is an affogato traditionally built with the ice cream placed first and the espresso poured last?', ARRAY['It doesn''t matter what order they''re combined in', 'The espresso needs to be poured hot, right before serving, for the contrast to work -- so it''s pulled last, not left waiting', 'Ice cream needs time to soften before espresso is added', 'This order is purely aesthetic with no functional reason'], 1, 'The whole appeal depends on a genuinely hot shot meeting cold ice cream, which means pulling the espresso last, right before serving, not letting it sit and cool.'),
('affogato-ch2-q1', 'affogato-ch2', 1, 'How does using a wider glass or bowl change an affogato compared to a smaller glass?', ARRAY['It has no real effect on the final result', 'It spreads the shot across more ice cream, melting it more slowly and keeping distinct pockets of ice cream and coffee for longer', 'It makes the espresso taste weaker', 'Wider glasses are only used for iced coffee, not affogato'], 1, 'A wider vessel spreads the same amount of hot espresso over more ice cream, slowing the melt and keeping the two more distinct for longer than a smaller glass would.'),
('sensory-cupping-ch1-q1', 'sensory-cupping-ch1', 1, 'Why does cupping use a standardized method instead of normal brewing methods like pour-over or espresso?', ARRAY['Standardized methods produce better-tasting coffee', 'It removes variation from brewer skill and equipment, so differences reflect the coffee itself, not the brewing', 'Cupping is simply faster than other methods', 'There''s no real reason -- it''s just tradition'], 1, 'Cupping strips away the variation ordinary brewing introduces, so what you''re actually tasting differences in is the coffee, not inconsistent technique.'),
('sensory-cupping-ch2-q1', 'sensory-cupping-ch2', 1, 'Why must every bowl in a cupping session be steeped for exactly the same amount of time?', ARRAY['Timing doesn''t actually matter for cupping', 'Inconsistent steep times would reintroduce the same kind of uncontrolled variation cupping is designed to eliminate', 'It only matters when comparing more than five coffees', 'Longer steeping always improves the coffee''s flavor'], 1, 'The whole point of cupping is controlling variables for a fair comparison -- inconsistent timing between bowls would undermine that fairness.'),
('sensory-cupping-ch3-q1', 'sensory-cupping-ch3', 1, 'What happens during the ''breaking the crust'' step in cupping?', ARRAY['The bowls are stirred vigorously to cool them faster', 'A spoon gently pushes aside the floating crust of grounds while leaning in to smell what''s released', 'The grounds are strained out entirely before tasting', 'This step doesn''t actually involve smelling anything'], 1, 'Breaking the crust releases trapped aromatics from just beneath the surface, often making it the most intense aromatic moment in the whole process.'),
('sensory-cupping-ch4-q1', 'sensory-cupping-ch4', 1, 'What''s the main difference between pleasant acidity and unpleasant sourness in coffee tasting?', ARRAY['There is no real difference -- they''re the same thing', 'Pleasant acidity tends to feel bright and fade cleanly; sourness tends to linger unpleasantly or feel flat', 'Acidity only applies to iced coffee, sourness only to hot coffee', 'Sourness is always preferred by professional tasters'], 1, 'Both can register as initial sharpness, but pleasant acidity resolves cleanly and brightly, while sourness tends to linger or feel flat and unpleasant.'),
('sensory-cupping-ch5-q1', 'sensory-cupping-ch5', 1, 'Is a lingering aftertaste always considered a negative quality in coffee tasting?', ARRAY['Yes, a clean finish is always preferred', 'No -- a lingering finish can be positive if what lingers is pleasant, like chocolate or dried fruit notes', 'Aftertaste isn''t something professional tasters actually evaluate', 'Only sourness can linger; acidity always fades quickly'], 1, 'Whether a lingering finish is good or bad depends on what''s actually lingering -- pleasant, complex notes versus harsh or bitter ones.'),
('sensory-cupping-ch6-q1', 'sensory-cupping-ch6', 1, 'Why does a cupping scoresheet break a coffee down into individual categories rather than just giving one overall score?', ARRAY['It''s purely a formality with no real benefit', 'It forces careful attention to each specific quality and makes it possible to say exactly where one coffee outperforms another', 'Individual scoring is faster than an overall impression', 'Scoresheets are only used for coffees scoring above 85 points'], 1, 'Breaking scoring into categories forces deliberate attention to each quality individually, making real, specific comparison possible rather than just a vague overall preference.'),
('cafe-management-ch1-q1', 'cafe-management-ch1', 1, 'What are the three real cost categories behind a single menu item, beyond just the beans?', ARRAY['Only ingredient cost matters', 'Ingredient cost, labor cost, and a share of overhead', 'Just labor and rent, ingredients are negligible', 'Menu items have no real costs beyond the coffee itself'], 1, 'A complete costing accounts for ingredients, labor time, and a proportional share of overhead -- missing any of these understates the true cost.'),
('cafe-management-ch2-q1', 'cafe-management-ch2', 1, 'Why is pricing based purely on matching competitor prices risky?', ARRAY['It''s not risky at all -- competitor pricing is the safest approach', 'Without knowing your own true costs first, a competitive-looking price might not actually cover what it costs you to make the drink', 'Competitors always price things correctly', 'Margin doesn''t matter as long as prices look similar to competitors'], 1, 'A price that looks reasonable next to competitors can still fail to cover your own real costs if you haven''t calculated those costs first.'),
('cafe-management-ch3-q1', 'cafe-management-ch3', 1, 'What''s a real cost of overstaffing that''s easy to overlook because it doesn''t show up as one big obvious expense?', ARRAY['Overstaffing has no real downside', 'Paying for staff hours that demand doesn''t actually require, which adds up significantly over time', 'Overstaffed shifts always run out of ingredients faster', 'It only matters on weekends'], 1, 'Overstaffing''s cost is easy to underestimate precisely because it''s spread across many shifts rather than appearing as one obvious loss.'),
('cafe-management-ch4-q1', 'cafe-management-ch4', 1, 'Why does drink quality often drift between baristas without a consistent, deliberate training process?', ARRAY['It doesn''t -- baristas naturally converge on identical technique', 'Each barista tends to develop their own habits and shortcuts over time without a shared standard to train against', 'Training has no real effect on consistency', 'Only new hires need training; experienced staff never drift'], 1, 'Without a shared, deliberate standard, individual habits and shortcuts naturally diverge over time, especially for judgment-based decisions.'),
('cafe-management-ch5-q1', 'cafe-management-ch5', 1, 'What does tracking waste specifically reveal that just looking at sales numbers doesn''t?', ARRAY['Nothing -- sales data alone tells the whole story', 'Whether an item that''s selling fine is also quietly losing margin to a high waste rate', 'Waste tracking is only useful for tax purposes', 'It reveals which staff member is the fastest'], 1, 'An item can look successful by sales alone while actually losing real margin to waste that sales figures wouldn''t show on their own.'),
('cafe-management-ch6-q1', 'cafe-management-ch6', 1, 'Why might a shorter, simpler menu actually outperform a longer, more ambitious one?', ARRAY['Customers always prefer fewer choices regardless of quality', 'A team stretched across too many items may execute none of them consistently well, especially during a rush', 'Shorter menus are always cheaper to source', 'There''s no real tradeoff -- more items is always better'], 1, 'Each additional item adds real complexity; a team that''s stretched too thin across too many items risks inconsistent execution on all of them, not just the newer ones.'),
('cafe-management-ch7-q1', 'cafe-management-ch7', 1, 'Why does effective rush management depend so much on decisions made before the rush actually happens?', ARRAY['It doesn''t -- the best baristas improvise well regardless of preparation', 'Workflow, station layout, and staff roles decided in advance prevent the confusion and wasted movement that slow a team down under real pressure', 'Rushes are entirely unpredictable and can''t be planned for at all', 'Only the barista on espresso needs a defined role'], 1, 'Layout and role clarity decided in advance prevent the wasted motion and confusion that would otherwise slow a team down exactly when speed matters most.'),
('cafe-management-ch8-q1', 'cafe-management-ch8', 1, 'Why does consistency in customer experience matter more than one exceptional interaction?', ARRAY['Consistency doesn''t actually matter to customers', 'An inconsistent experience -- great sometimes, poor other times -- tends to feel less reliable and gets remembered more negatively than steady, good-enough service', 'Customers only remember their very first visit', 'One exceptional visit always outweighs several average ones'], 1, 'Inconsistency itself is what customers tend to notice and remember unfavorably, more than any single good or bad interaction on its own.'),
('cafe-management-ch9-q1', 'cafe-management-ch9', 1, 'Why is checking key business numbers regularly, not just occasionally, actually important?', ARRAY['Regular checking has no real advantage over occasional checking', 'A problem caught early from a drifting number is far easier and cheaper to correct than one discovered much later', 'Numbers only need to be checked once per year', 'Vanity metrics like transaction count are the most important numbers to track'], 1, 'Catching a drifting number early makes correction far easier than discovering the same problem much later, after it''s had time to compound.')
ON CONFLICT (id) DO NOTHING;

-- Total: 52 chapters given real content, objectives, and one quiz question each
